infix using "C:\ENQBASE\SUIVICFCRTM\DBCONCAT\CHDB.dct"

label variable uf1      "Numéro de grappe"
label variable uf2      "numéro de ménage"
label variable uf3      "Numéro de ligne de l'enfant"
label variable uf3n     "Nom de l'enfant"
label variable uf4n     "Nom de la Mère /Gardien(ne)"
label variable uf4      "Numèro de la Mère / Gardien(e)"
label variable uf5      "Code Enquêteur"
label variable uf6      "Code Superviseur"
label variable uf7      "Date de l'Interview"
label variable uf7d     "Jour de l'interview"
label variable uf7m     "Mois de l'interview"
label variable uf7y     "Année de l'interview"
label variable uf9      "Un des membres de votre équipe a-t-il déjà interviewé ce répondant sur un autre "
label variable uf10     "Consentement"
label variable uf17     "Résultat de l'interview pour enfant de moins de 5 ans"
label variable uf8      "Heure de Début de l'Interview"
label variable uf8h     "Heure de Début de l'Interview-Heure"
label variable uf8m     "Heure de Début de l'Interview-Minutes"
label variable uf11     "Heure de la Fin Interview"
label variable uf11h    "Heure de la Fin Interview-Heure"
label variable uf11m    "Heure de la Fin Interview-Minutes"
label variable uf12     "Langue du Questionnaire"
label variable uf13     "Langue de l'interview"
label variable uf14     "Langue Maternelle du répondant"
label variable uf15     "Utilisation d'un Interprète"
label variable ub1      "Date de Naissance de l'enfant"
label variable ub1d     "Jour de Naissance de l'enfant"
label variable ub1m     "Mois de Naissance de l'enfant"
label variable ub1y     "Année de Naissance de l'enfant"
label variable ub2      "Âge de l'enfant"
label variable ub6      "Est-ce que (nom) a déjà fréquenté un programme d’éducation préscolaire, tel que "
label variable ub7      "A n’importe quel moment depuis Septembre 2018, a-t-il/elle assisté à (programmes"
label variable ub8      "Est-ce qu’il/elle fréquente actuellement un  (programme mentionné à UB6)?"
label variable ub9      "Est-ce que (nom) est couvert(e) par une assurance santé ?"
label variable ub10     "Par quel type d’assurance santé (nom) est-il/elle couvert (e) ?"
label variable ub10a    "Assurance santé:ORGANISATION  MUTUELLE DE SANTE/ ASSURANCE SANTE A BASE COMMUNAU"
label variable ub10b    "Assurance santé:ASSURANCE SANTE DE L’EMPLOYEUR"
label variable ub10c    "Assurance santé:SECURITE SOCIALE"
label variable ub10d    "Assurance santé:AUTRE ASSURANCE SANTE PRIVEE ACHETEE"
label variable ub10x    "Assurance santé: Autre"
label variable ub10nr   "Assurance santé: Non réponse"
label variable br1      "Est-ce que (nom) a un Acte de naissance ?"
label variable br2      "La naissance de (nom) a-t-elle été enregistrée/déclarée auprès de l’état civil ?"
label variable br3      "Savez-vous comment enregistrer la naissance de (nom) ?"
label variable bd2      "Est-ce que (nom) a été allaité ?"
label variable bd3      "Est-ce que (nom) est toujours allaité ?"
label variable bd4      "Hier, durant le jour ou la nuit, est-ce que (nom) a bu quelque chose au biberon "
label variable bd5      "Hier, durant le jour ou la nuit, est-ce que (nom) a bu des Sels de Réhydratation"
label variable bd6      "Hier, durant le jour ou la nuit, est-ce que (nom) a bu ou mangé des vitamines ou"
label variable bd7a     "Hier, durant le jour ou la nuit, est-ce que (nom) a bu : EAU SIMPLE"
label variable bd7b     "Hier, durant le jour ou la nuit, est-ce que (nom) a bu : JUS OU BOISSON A BASE D"
label variable bd7c     "Hier, durant le jour ou la nuit, est-ce que (nom) a bu : BOUILLON CLAIR"
label variable bd7d     "Hier, durant le jour ou la nuit, est-ce que (nom) a bu : LAIT MATERNISE"
label variable bd7d1    "Combien de fois (nom) a-t-il bu du lait maternisé ?"
label variable bd7e     "Hier, durant le jour ou la nuit, est-ce que (nom) a bu : Du lait d’animal, qu’il"
label variable bd7e1    "Combien de fois (nom) a-t-il bu du lait"
label variable bd7x     "Autres liquides"
label variable bd8a     "Juste pour être sûre, est-ce que (nom) a mangé du : YAOURT"
label variable bd8a1    "Combien de fois (nom) a-t-il/elle mangé du yaourt ?"
label variable bd8b     "Juste pour être sûre, est-ce que (nom) a mangé du : De la nourriture pour bébé t"
label variable bd8c     "Du pain, riz, pâtes, porridge, ou autres aliments à base de grains ?"
label variable bd8d     "Courge, carotte, citrouille, patate douce qui sont jaune ou orange à l’intérieur"
label variable bd8e     "Des pommes de terre, de l’igname, du manioc, de la patate douce ou autre nourrit"
label variable bd8f     "N’importe quel légume à feuilles vert foncé riche en Vit-A comme Epinard, Amaran"
label variable bd8g     "Mangues mures ou des papayes mures ou  d’autres fruits locaux riches en Vit-A co"
label variable bd8h     "Tout autre fruit et légume, parmi les plus communément consommés comme Avocat, A"
label variable bd8i     "Du foie, des rognons, du cœur ou autres abats ?"
label variable bd8j     "Toute autre viande comme du bœuf, du porc, de l’agneau, de la chèvre, du poulet,"
label variable bd8k     "Des oeufs ?"
label variable bd8l     "Du poisson ou des crustacés, frais ou séchés ?"
label variable bd8m     "Des haricots, petits pois, lentilles ou noix (arachides, amandes, etc.), y compr"
label variable bd8n     "Du fromage ou autre aliment fait avec du lait d’animal"
label variable bd8o     "Des chenilles, escargots, termites"
label variable bd8x     "Autre aliment solide, semi-solide ou mou ?"
label variable bd9      "Combien de fois (nom) a-t-il/elle mangé des aliments solides, semi-solides ou mo"
label variable bd8dummy "Dummy for BD8 explanation"
label variable im2      "Avez-vous un carnet/carte de vaccinations ou un document d’un agent de santé pri"
label variable im3      "Avez-vous déjà eu un/une carnet/carte de vaccinations ou un document d’un agent "
label variable im5      "Puis-je voir le carnet/carte (et/ou) l’autre document ?"
label variable im6b     "Date de vaccination BCG (à la naissance)"
label variable im6bd    "Jour de Vaccination BCG (à la naissance)"
label variable im6bm    "Mois de vaccination BCG (à la naissance)"
label variable im6by    "Année de vaccination BCG (à la naissance)"
label variable im6p     "Date de vaccination Polio (VPO) (à la naissance) VPO0"
label variable im6p0d   "Jour de vaccination Polio (VPO) (à la naissance) VPO0"
label variable im6p0m   "Mois de vaccination Polio (VPO) (à la naissance) VPO0"
label variable im6p0y   "Année de vaccination Polio (VPO) (à la naissance) VPO0"
label variable im6p1    "Date de vaccination Polio (VPO) 1 VPO1"
label variable im6p1d   "Jour de vaccination Polio (VPO) 1 VPO1"
label variable im6p1m   "Mois de vaccination Polio (VPO) 1 VPO1"
label variable im6p1y   "Année de vaccination Polio (VPO) 1 VPO1"
label variable im6p2    "Date de vaccination Polio (VPO) 2 VPO2"
label variable im6p2d   "Jour de vaccination Polio (VPO) 2 VPO2"
label variable im6p2m   "Mois de vaccination Polio (VPO) 2 VPO2"
label variable im6p2y   "Année de vaccination Polio (VPO) 2 VPO2"
label variable im6p3    "Date de vaccination Polio (VPO) 3 VPO3"
label variable im6p3d   "Jour de vaccination Polio (VPO) 3 VPO3"
label variable im6p3m   "Mois de vaccination Polio (VPO) 3 VPO3"
label variable im6p3y   "Année de vaccination Polio (VPO) 3 VPO3"
label variable im6i     "Date de vaccination Polio (VPI) VPI"
label variable im6id    "Jour de vaccination Polio (VPI) VPI"
label variable im6im    "Mois de vaccination Polio (VPI) VPI"
label variable im6iy    "Année de vaccinationPolio (VPI) VPI"
label variable im6penta1 "Date de vaccination Pentavalent (DTCOQHibHepB) 1 Penta1"
label variable im6penta1d "Jour de vaccination Pentavalent (DTCOQHibHepB) 1 Penta1"
label variable im6penta1m "Mois de vaccination Pentavalent (DTCOQHibHepB) 1 Penta1"
label variable im6penta1y "Année de vaccination Pentavalent (DTCOQHibHepB) 1 Penta1"
label variable im6penta2 "Date de vaccination Pentavalent (DTCOQHibHepB) 2 Penta 2"
label variable im6penta2d "Jour de vaccination Pentavalent (DTCOQHibHepB) 2 Penta 2"
label variable im6penta2m "Mois de vaccination Pentavalent (DTCOQHibHepB) 2 Penta 2"
label variable im6penta2y "Année de vaccination Pentavalent (DTCOQHibHepB) 2 Penta 2"
label variable im6penta3 "Date de vaccination Pentavalent (DTCOQHibHepB) 3 Penta3"
label variable im6penta3d "Jour de vaccination Pentavalent (DTCOQHibHepB) 3 Penta 3"
label variable im6penta3m "Mois de vaccination Pentavalent (DTCOQHibHepB) 3 Penta 3"
label variable im6penta3y "Annéede vaccination Pentavalent (DTCOQHibHepB) 3 Penta 3"
label variable im6pcv1  "Date de vaccination Pneumococcal (Conjugué) 1 PCV1"
label variable im6pcv1d "Jour de vaccination Pneumococcal (Conjugué) 1 PCV1"
label variable im6pcv1m "Mois de vaccination Pneumococcal (Conjugué) 1 PCV1"
label variable im6pcv1y "Année de vaccination Pneumococcal (Conjugué) 1 PCV1"
label variable im6pcv2  "Date de vaccination Pneumococcal (Conjugué) 1 PCV2"
label variable im6pcv2d "Jour de vaccination Pneumococcal (Conjugué) 1 PCV2"
label variable im6pcv2m "Mois de vaccination Pneumococcal (Conjugué) 1 PCV2"
label variable im6pcv2y "Année de vaccination Pneumococcal (Conjugué) 1 PCV2"
label variable im6pcv3  "Date de vaccination Pneumococcal (Conjugué) 1 PCV3"
label variable im6pcv3d "Jour de vaccinationPneumococcal (Conjugué) 1 PCV3"
label variable im6pcv3m "Mois de vaccination Pneumococcal (Conjugué) 1 PCV3"
label variable im6pcv3y "Année de vaccination Pneumococcal (Conjugué) 1 PCV3"
label variable im6m     "Date de vaccination MMR (VAR)"
label variable im6md    "Jour de vaccination MMR (VAR)"
label variable im6mm    "Mois de vaccination MMR (VAR)"
label variable im6my    "Année de vaccination MMR (VAR)"
label variable im6y     "Date de vaccination Fièvre Jaune (FJ)"
label variable im6yd    "Jour de vaccination Fièvre Jaune (FJ)"
label variable im6ym    "Mois de vaccination Fièvre Jaune (FJ)"
label variable im6yy    "Année de vaccination Fièvre Jaune (FJ)"
label variable im8a     "Est-ce que (nom) a participé aux JNV, VPOT, 2016"
label variable im8b     "Est-ce que (nom) a participé aux JNV, VPOT, 2017"
label variable im9      "En plus de ce qui est enregistré dans le document que vous nous avez montré, est"
label variable im11     "Est-ce que (nom) a déjà reçu des vaccinations pour l’empêcher d’attraper des mal"
label variable im12a    "Est-ce que (nom) a participé aux campagnes ou journées nationales de vaccination"
label variable im12b    "Est-ce que (nom) a participé aux campagnes ou journées nationales de vaccination"
label variable im14     "Est-ce que (nom) a déjà reçu le vaccin du BCG contre la tuberculose – c’est-à-di"
label variable im16     "Est-ce que  (nom) a déjà reçu un « vaccin sous forme de gouttes dans la bouche »"
label variable im17     "Est-ce que les premières gouttes de Polio ont été données dans les 2 premières s"
label variable im18     "Combien de fois les gouttes de Polio ont été données ?"
label variable im19     "La dernière fois que (nom) a reçu des gouttes de Polio, est-ce qu’il/elle a égal"
label variable im20     "Est-ce que (nom) a déjà reçu le vaccin Pentavalent– c’est-à-dire une injection d"
label variable im21     "Combien de fois le vaccin Pentavalent a été donné ?"
label variable im22     "Est-ce que (nom) a déjà reçu le vaccin Pneumoccocal Conjugué - PCV– c’est-à-dire"
label variable im23     "Combien de fois le vaccin Pneumoccocal Conjugué PCV a été donné ?"
label variable im26     "Est-ce que (nom) a déjà reçu le VAR c’est-à-dire une injection dans le bras à l’"
label variable im27     "Est-ce que (nom) a déjà reçu une injection contre la Fièvre Jaune c’est-à-dire u"
label variable im28     "Au cours des 6 derniers mois, est-ce (nom) a reçu la vitamine A"
label variable im29     "Au cours des 6 derniers mois, est-ce qu (nom) a reçu un traitement de déparasita"
label variable ca0a     "Au cours des derniers 6 mois , avez-vous reçu 1 kit familial d'enfant pour (nom)"
label variable ca0b     "Au cours des 6 derniers mois , avez- vous utilisé pour (nom) les médicaments qui"
label variable ca1      "Est-ce que (nom) a eu la diarrhée au cours des deux dernières semaines ?"
label variable ca3      "Je voudrais savoir quelle quantité de liquides à boire a été donnée à (nom) dura"
label variable ca4      "Pendant que (nom) avait la diarrhée, a-t-il/elle reçut à manger  moins que d’hab"
label variable ca5      "Avez-vous recherché des conseils ou un traitement contre la diarrhée de n’import"
label variable ca6      "Ou avez-vous cherché des conseils ou un traitement ?"
label variable ca6a     "Place sought care: HOPITAL GOUVERNEMENTAL"
label variable ca6b     "Place sought care: CENTRE DE SANTE GOUVERNEMENTAL"
label variable ca6c     "Place sought care: POSTE DE SANTE GOUVERNEMENTAL"
label variable ca6d     "Place sought care: AGENT DE SANTE COMMUNAUTAIRE"
label variable ca6e     "Place sought care: CLINIQUE MOBILE/STRATEGIE AVANCEE"
label variable ca6h     "Place sought care: AUTRE MEDICAL PUBLIC"
label variable ca6i     "Place sought care: HOPITAL PRIVE / CLINIQUE"
label variable ca6j     "Place sought care: MEDECIN PRIVE"
label variable ca6k     "Place sought care: PHARMACIE PRIVEE"
label variable ca6l     "Place sought care: AGENT DE SANTE COMMUNAUTAIRE (NON GOUVERNEMENTAL)"
label variable ca6m     "Place sought care: CLINIQUE MOBILE"
label variable ca6o     "Place sought care: AUTRE MEDICAL PRIVE"
label variable ca6p     "Place sought care: FAMILLE/AMIS"
label variable ca6q     "Place sought care: BOUTIQUE/MARCHE/RUE"
label variable ca6r     "Place sought care: PRATICIEN TRADITIONNEL"
label variable ca6x     "Place sought care: AUTRE"
label variable ca6nr    "Place sought care: Manquant"
label variable ca7a     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : SACHET DE SRO"
label variable ca7b     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : LIQUIDE SRO DEJA PREPARE"
label variable ca7c     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : ZINC COMPRIMES OU SIROP"
label variable ca7d     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : EAU POTABLE"
label variable ca7e     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : EAU DE RIZ"
label variable ca7f     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : POTAGE"
label variable ca7g     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : LAIT DE COCO"
label variable ca7h     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : LAIT DE SOJA"
label variable ca7i     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : LAIT DE COURGE"
label variable ca7j     "Quand (nom) a eu la diarrhée est-ce qu’il a eu : BOUILLIE"
label variable ca7k     "Quand (nom) a eu la diarrhée/ liquide racine"
label variable ca9      "Ou avez-vous eu le (SRO mentionné en CA7 [A] et/ou en CA7 [B]) ?"
label variable ca9a     "Nom de l’endroit : HOPITAL GOUVERNEMENTAL"
label variable ca9b     "Nom de l’endroit : CENTRE DE SANTE GOUVERNEMENTAL"
label variable ca9c     "Nom de l’endroit : POSTE DE SANTE GOUVERNEMENTAL"
label variable ca9d     "Nom de l’endroit : AGENT DE SANTE COMMUNAUTAIRE"
label variable ca9e     "Nom de l’endroit : CLINIQUE MOBILE/STRATEGIE AVANCEE"
label variable ca9h     "Nom de l’endroit : AUTRE MEDICAL PUBLIC Précisez"
label variable ca9i     "Nom de l’endroit : HOPITAL PRIVE / CLINIQUE"
label variable ca9j     "Nom de l’endroit : MEDECIN PRIVE"
label variable ca9k     "Nom de l’endroit : PHARMACIE PRIVEE"
label variable ca9l     "Nom de l’endroit : AGENT DE SANTE COMMUNAUTAIRE (NON GOUVERNEMENTAL)"
label variable ca9m     "Nom de l’endroit : CLINIQUE MOBILE"
label variable ca9o     "Nom de l’endroit : AUTRE MEDICAL PRIVE"
label variable ca9p     "Nom de l’endroit : FAMILLE/AMIS"
label variable ca9q     "Nom de l’endroit : BOUTIQUE/MARCHE/RUE"
label variable ca9r     "Nom de l’endroit : PRATICIEN TRADITIONNEL"
label variable ca9x     "Nom de l’endroit : AUTRE (préciser)"
label variable ca9z     "Nom de l'endroit : NSP / NE SE RAPPELLE PAS"
label variable ca9nr    "Nom de l'endroit : Manquant"
label variable ca11     "Ou avez-vous eu le zinc ?"
label variable ca11a    "Nom de l’endroit : HOPITAL GOUVERNEMENTAL"
label variable ca11b    "Nom de l’endroit : CENTRE DE SANTE GOUVERNEMENTAL"
label variable ca11c    "Nom de l’endroit : POSTE DE SANTE GOUVERNEMENTAL"
label variable ca11d    "Nom de l’endroit : AGENT DE SANTE COMMUNAUTAIRE"
label variable ca11e    "Nom de l’endroit : CLINIQUE MOBILE/STRATEGIE AVANCEE"
label variable ca11h    "Nom de l’endroit : AUTRE MEDICAL PUBLIC"
label variable ca11i    "Nom de l’endroit : HOPITAL PRIVE / CLINIQUE"
label variable ca11j    "Nom de l’endroit : MEDECIN PRIVE"
label variable ca11k    "Nom de l’endroit : PHARMACIE PRIVEE"
label variable ca11l    "Nom de l’endroit : AGENT DE SANTE COMMUNAUTAIRE (NON GOUVERNEMENTAL)"
label variable ca11m    "Nom de l’endroit : CLINIQUE MOBILE"
label variable ca11o    "Nom de l'endroit : AUTRE MEDICAL PRIVE"
label variable ca11p    "Nom de l'endroit : FAMILLE/AMIS"
label variable ca11q    "Nom de l'endroit : BOUTIQUE/MARCHE/RUE"
label variable ca11r    "Nom de l'endroit : PRATICIEN TRADITIONNEL"
label variable ca11x    "Nom de l'endroit : AUTRE (préciser)"
label variable ca11z    "Nom de l'endroit : NSP / NE SE RAPPELLE PAS"
label variable ca11nr   "Nom de l'endroit : Manquant"
label variable ca12     "Est-ce que quelque chose d’autre a été donnée pour traiter la diarrhée ?"
label variable ca13     "Qu’est-ce qui a été donné en plus pour traiter la diarrhée  ?"
label variable ca13a    "Autre traitement : ANTIBIOTIQUE"
label variable ca13b    "Autre traitement : ANTIMOTILITE (ANTI-DIARRHEIQUE)"
label variable ca13g    "Autre traitement : AUTRE COMPRIME OU SIROP"
label variable ca13h    "Autre traitement : COMPRIME OU SIROP INCONNU"
label variable ca13l    "Autre traitement : ANTIBIOTIQUE"
label variable ca13m    "Autre traitement : PAS ANTIBIOTIQUE"
label variable ca13n    "Autre traitement : INJECTION INCONNUE"
label variable ca13o    "Autre traitement : INTRAVEINEUSE (IV)"
label variable ca13q    "Autre traitement : REMEDE MAISON/ HERBE MEDICINALE"
label variable ca13x    "Autre traitement : AUTRE"
label variable ca13nr   "Autre traitement : NSP / NE SE RAPPELLE PAS"
label variable ca14     "A n’importe quel moment au cours des deux dernières semaines, est-ce que (nom) a"
label variable ca15     "À n’importe quel moment durant sa maladie, est-ce que (nom) a eu du sang prélevé"
label variable ca16     "A n’importe quel moment au cours des deux dernières semaines, est-ce que (nom) a"
label variable ca17     "A n’importe quel moment au cours des deux dernières semaines, est-ce que (nom) a"
label variable ca18     "La respiration rapide ou les difficultés respiratoires étaient-elles dues à un p"
label variable ca20     "Avez-vous recherché des conseils ou un traitement pour la maladie quelque part ?"
label variable ca21     "L'endroit où on a recherché des conseils ou un traitement ?"
label variable ca21a    "L'endroit où on a recherché conseils ou traitement: HOPITAL GOUVERNEMENTAL"
label variable ca21b    "L'endroit où on a recherché conseils ou traitement: CENTRE DE SANTE GOUVERNEMENT"
label variable ca21c    "L'endroit où on a recherché conseils ou traitement: POSTE DE SANTE GOUVERNEMENTA"
label variable ca21d    "L'endroit où on a recherché conseils ou traitement: AGENT DE SANTE COMMUNAUTAIRE"
label variable ca21e    "L'endroit où on a recherché conseils ou traitement: CLINIQUE MOBILE/STRATEGIE AV"
label variable ca21h    "L'endroit où on a recherché conseils ou traitement: AUTRE MEDICAL PUBLIC"
label variable ca21i    "L'endroit où on a recherché conseils ou traitement: HOPITAL PRIVE / CLINIQUE"
label variable ca21j    "L'endroit où on a recherché conseils ou traitement: MEDECIN PRIVE"
label variable ca21k    "L'endroit où on a recherché conseils ou traitement: PHARMACIE PRIVEE"
label variable ca21l    "L'endroit où on a recherché conseils ou traitement: AGENT DE SANTE COMMUNAUTAIRE"
label variable ca21m    "L'endroit où on a recherché conseils ou traitement: CLINIQUE MOBILE"
label variable ca21o    "L'endroit où on a recherché conseils ou traitement: AUTRE MEDICAL PRIVE"
label variable ca21p    "L'endroit où on a recherché conseils ou traitement: FAMILLE/AMIS"
label variable ca21q    "L'endroit où on a recherché conseils ou traitement: Shop / Market / Street"
label variable ca21r    "L'endroit où on a recherché conseils ou traitement: PRATICIEN TRADITIONNEL"
label variable ca21x    "L'endroit où on a recherché conseils ou traitement: Autre"
label variable ca21nr   "L'endroit où on a recherché conseils ou traitement: Manquant"
label variable ca22     "A n’importe quel moment de sa maladie, est-ce que (nom) a reçu un médicament pou"
label variable ca23     "Quel médicament (nom) a-t-il/elle reçu ?"
label variable ca23a    "Médicament reçu : ARTESUNATE + AMODIAQUINE"
label variable ca23b    "Médicament reçu : ARTESUNATE+LUMEFANTRINE"
label variable ca23c    "Médicament reçu : SP/ FANSIDAR"
label variable ca23d    "Médicament reçu : CHLOROQUINE"
label variable ca23e    "Médicament reçu : AMODIAQUINE"
label variable ca23f    "Médicament reçu : QUININE COMPERIMES"
label variable ca23g    "Médicament reçu : INJECTION/ IV"
label variable ca23h    "Médicament reçu : ARTESUNATE INJECTION/ IV"
label variable ca23i    "Médicament reçu:  ARTESUNATE EN SUPPOSITOIRE"
label variable ca23j    "Médicament reçu : AUTRE INJECTION / IV"
label variable ca23k    "Médicament reçu : AUTRE ANTI-PALUDIQUE"
label variable ca23l    "Médicament reçu : AMOXICILLIN"
label variable ca23m    "Médicament reçu : COTRIMOXAZOLE"
label variable ca23n    "Médicament reçu : AUTRES COMPRIMES OU SIROP ANTIBIOTIQUE"
label variable ca23o    "Médicament reçu : AUTRE INJECTION/IV ANTIBIOTIQUE"
label variable ca23r    "Médicament reçu : PARACETAMOL/PANADOL/ACETAMINONPHEN"
label variable ca23s    "Médicament reçu : ASPIRINE"
label variable ca23t    "Médicament reçu : IBUPROFEN"
label variable ca23x    "Médicament reçu : AUTRE"
label variable ca23z    "Médicament reçu : NSP"
label variable ca23nr   "Médicament reçu : Manquant"
label variable ca25     "L'endroit où on a obtenu l'antibiotique  (nom du médicament de CA23, codes L à O"
label variable ca25a    "L'endroit où on a obtenu l'antibiotique : HOPITAL GOUVERNEMENTAL"
label variable ca25b    "L'endroit où on a obtenu l'antibiotique : CENTRE DE SANTE GOUVERNEMENTAL"
label variable ca25c    "L'endroit où on a obtenu l'antibiotique : POSTE DE SANTE GOUVERNEMENTAL"
label variable ca25d    "L'endroit où on a obtenu l'antibiotique : AGENT DE SANTE COMMUNAUTAIRE"
label variable ca25e    "L'endroit où on a obtenu l'antibiotique : CLINIQUE MOBILE/STRATEGIE AVANCEE"
label variable ca25h    "L'endroit où on a obtenu l'antibiotique : AUTRE MEDICAL PUBLIC"
label variable ca25i    "L'endroit où on a obtenu l'antibiotique : HOPITAL PRIVE / CLINIQUE"
label variable ca25j    "L'endroit où on a obtenu l'antibiotique : MEDECIN PRIVE"
label variable ca25k    "L'endroit où on a obtenu l'antibiotique : PHARMACIE PRIVEE"
label variable ca25l    "L'endroit où on a obtenu l'antibiotique : AGENT DE SANTE COMMUNAUTAIRE (NON GOUV"
label variable ca25m    "L'endroit où on a obtenu l'antibiotique : CLINIQUE MOBILE"
label variable ca25o    "L'endroit où on a obtenu l'antibiotique : AUTRE MEDICAL PRIVE"
label variable ca25p    "L'endroit où on a obtenu l'antibiotique : FAMILLE/AMIS"
label variable ca25q    "L'endroit où on a obtenu l'antibiotique : BOUTIQUE/MARCHE/RUE"
label variable ca25r    "L'endroit où on a obtenu l'antibiotique : PRATICIEN TRADITIONNEL"
label variable ca25x    "L'endroit où on a obtenu l'antibiotique : AUTRE"
label variable ca25z    "L'endroit où on a obtenu l'antibiotique : NSP / NE SE RAPPELLE PAS"
label variable ca25nr   "L'endroit où on a obtenu l'antibiotique : Manquant"
label variable ca27     "L' endroit où on a  obtenu l'antipaludéen (nom du médicament de CA23, codes A à "
label variable ca27a    "L'endroit où on a obtenu l'antipaludéen : HOPITAL GOUVERNEMENTAL"
label variable ca27b    "L'endroit où on a obtenu l'antipaludéen : CENTRE DE SANTE GOUVERNEMENTAL"
label variable ca27c    "L'endroit où on a obtenu l'antipaludéen :POSTE DE SANTE GOUVERNEMENTAL"
label variable ca27d    "L'endroit où on a obtenu l'antipaludéen : AGENT DE SANTE COMMUNAUTAIRE"
label variable ca27e    "L'endroit où on a obtenu l'antipaludéen :CLINIQUE MOBILE/STRATEGIE AVANCEE"
label variable ca27h    "L'endroit où on a obtenu l'antipaludéen : AUTRE MEDICAL PUBLIC"
label variable ca27i    "L'endroit où on a obtenu l'antipaludéen :HOPITAL PRIVE / CLINIQUE"
label variable ca27j    "L'endroit où on a obtenu l'antipaludéen :  MEDECIN PRIVE"
label variable ca27k    "L'endroit où on a obtenu l'antipaludéen : PHARMACIE PRIVEE"
label variable ca27l    "L'endroit où on a obtenu l'antipaludéen :AGENT DE SANTE COMMUNAUTAIRE (NON GOUVE"
label variable ca27m    "L'endroit où on a obtenu l'antipaludéen : CLINIQUE MOBILE"
label variable ca27o    "L'endroit où on a obtenu l'antipaludéen : AUTRE MEDICAL PRIVE"
label variable ca27p    "L'endroit où on a obtenu l'antipaludéen : FAMILLE/AMIS"
label variable ca27q    "L'endroit où on a obtenu l'antipaludéen : BOUTIQUE/MARCHE/RUE"
label variable ca27r    "L'endroit où on a obtenu l'antipaludéen :PRATICIEN TRADITIONNEL"
label variable ca27x    "L'endroit où on a obtenu l'antipaludéen : AUTRE"
label variable ca27z    "L'endroit où on a obtenu l'antipaludéen : NSP / NE SE RAPPELLE PAS"
label variable ca27nr   "L'endroit où on a obtenu l'antipaludéen : MANQUANT"
label variable ca29     "A pris le premier médicament après le début de la fièvre"
label variable an1      "Numéro de grappe"
label variable an2      "numéro du ménage"
label variable an3n     "Nom de l'enfant"
label variable an3      "Numero de ligne de l'enfant"
label variable an4      "Âge de l'enfant"
label variable an5n     "Nom de la mère"
label variable an5      "Numero de ligne de la mère"
label variable an6      "Numero de l'enquêteur"
label variable an7n     "Nom du mesureur"
label variable an7      "Code du mesureur"
label variable an8      "Pois de l'enfant  (kilogrammes)"
label variable an9      "Est-ce que l’enfant a été déshabillé jusqu’au   minimum"
label variable an11     "Longueur ou poids de l'enfant (centimetres)"
label variable an12     "Enfant mesuré debout ou couché"
label variable an13     "Date de mesure"
label variable an13d    "Jour de mesure"
label variable an13m    "Mois de mesure"
label variable an13y    "Année de mesure"
label variable an14     "Un autre enfant de moins de 5 ans non mesuré"
label variable an12b    "MUAC"

#delimit ;
label define UF7M    
     1 "janvier"
     2 "février"
     3 "mars"
     4 "avril"
     5 "mai"
     6 "juin"
     7 "juillet"
     8 "août"
     9 "septembre"
    10 "octobre"
    11 "novembre"
    12 "décembre"
;
label define UF9     
     1 "OUI, DEJA INTERVIEWE"
     2 "NON, PREMIERE INTERVIEW"
;
label define UF10    
     1 "OUI, PERMISSION DONNEE"
     2 "NON, PERMISSION PAS DONNEE"
;
label define UF17    
     1 "COMPLETE"
     2 "PAS A LA MAISON"
     3 "REFUSE"
     4 "PARTIELLEMENT COMPLETE"
     5 "EN INCAPACITE"
     6 "PAS DE CONSENTEMENT D’UN ADULTE POUR CETTE REPONDANTE AGEE DE 15-17 ANS"
    96 "AUTRE"
;
label define UF8H    
    99 "NON REPONSE"
;
label define UF8M    
    99 "NON REPONSE"
;
label define UF11H   
    99 "NON REPONSE"
;
label define UF11M   
    99 "NON REPONSE"
;
label define UF12    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define UF13    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define UF14    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define UF15    
     1 "OUI, QUESTIONNAIRE ENTIER"
     2 "OUI, PARTIES DU QUESTIONNAIRE"
     3 "NON, PAS UTILISE"
     9 "NON REPONSE"
;
label define UB1D    
    98 "NSP"
    99 "Pas de réponse"
;
label define UB1M    
    98 "NSP"
    99 "NON REPONSE"
;
label define UB1Y    
  9999 "NON REPONSE"
;
label define UB6     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define UB7     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define UB8     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define UB9     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define BR1     
     1 "OUI, VU"
     2 "OUI, PAS VU"
     3 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BR2     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BR3     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define BD2     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD3     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD4     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD5     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD6     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7A    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7B    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7C    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7D    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7D1   
     7 "7+"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7E    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7E1   
     7 "7+"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD7X    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8A    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8A1   
     7 "7+"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8B    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8C    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8D    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8E    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8F    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8G    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8H    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8I    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8J    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8K    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8L    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8M    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8N    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8O    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD8X    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define BD9     
     7 "7+"
     8 "DK"
     9 "NON REPONSE"
;
label define BD8DUMMY
     1 "Continuer"
;
label define IM2     
     1 "OUI, A SEULEMENT UN CARNET/CARTE"
     2 "OUI, A SEULEMENT UN AUTRE DOCUMENT"
     3 "OUI, A CARNET/CARTE  ET AUTRE DOCUMENT"
     4 "NON, N’A NI CARNET/CARTE NI AUTRE DOCUMENT"
     9 "NON REPONSE"
;
label define IM3     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define IM5     
     1 "OUI, CARNET/CARTE SEULEMENT VU"
     2 "OUI, AUTRE DOCUMENT SEULEMENT VU"
     3 "OUI, CARNET/CARTE ET AUTRE DOCUMENT VUS"
     4 "NI CARNET/CARTE NI AUTRE DOCUMENT VU"
     5 "NON CARTE, CARNET/ CARTE RETNU AU CENTRE DE SANTE"
     9 "NON REPONSE"
;
label define IM6BD   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6BM   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6BY   
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6P0D  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P0M  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P0Y  
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6P1D  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P1M  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P1Y  
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6P2D  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P2M  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P2Y  
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6P3D  
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6P3M  
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
    99 "NO RESPONSE"
;
label define IM6P3Y  
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6ID   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6IM   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6IY   
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PENTA1D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA1M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA1Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PENTA2D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA2M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA2Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PENTA3D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA3M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PENTA3Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PCV1D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV1M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV1Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PCV2D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV2M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV2Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6PCV3D
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV3M
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6PCV3Y
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6MD   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6MM   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6MY   
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM6YD   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6YM   
     0 "NON SIGNALÉ"
    44 "ENREGSTRÉ SUR LA CARTE"
    66 "DECLARÉ PAR LA MAMAN"
    99 "NON REPONSE"
;
label define IM6YY   
     0 "NON SIGNALÉ"
  4444 "ENREGSTRÉ SUR LA CARTE"
  6666 "DECLARÉ PAR LA MAMAN"
  9999 "NON REPONSE"
;
label define IM8A    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM8B    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM9     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM11    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM12A   
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM12B   
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM14    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM16    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM17    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM18    
     8 "NSP"
     9 "NON REPONSE"
;
label define IM19    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM20    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM21    
     8 "NSP"
     9 "NON REPONSE"
;
label define IM22    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM23    
     8 "NSP"
     9 "NON REPONSE"
;
label define IM26    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM27    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define IM28    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define IM29    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define CA0A    
     1 "OUI, UNE FOIS"
     2 "OUI, DEUX FOIS"
     3 "PAS DANS LES 6 DERNIERS MOIS"
     4 "JAMAIS RE9U"
     8 "NSP"
;
label define CA0B    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA1     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA3     
     1 "BEAUCOUP MOINS"
     2 "UN PEU MOINS"
     3 "A PEU PRES LA MEME CHOSE"
     4 "PLUS"
     5 "RIEN A BOIRE"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA4     
     1 "BEAUCOUP MOINS"
     2 "UN PEU MOINS"
     3 "A PEU PRES LA MEME CHOSE"
     4 "PLUS"
     5 "A STOPPE L’ALIMENTATION"
     6 "N’A JAMAIS DONNE A MANGER"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA5     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA7A    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA7B    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA7C    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA7D    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA7E    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7F    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7G    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7H    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7I    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7J    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA7K    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "MANQUANT"
;
label define CA12    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON RESPONSE"
;
label define CA14    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA15    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA16    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA17    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA18    
     1 "PROBLEMES DANS LA POITRINE SEULEMENT"
     2 "NEZ BLOQUE OU QUI COULAIT"
     3 "LES DEUX"
     6 "AUTRE"
     8 "NSP"
;
label define CA20    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA22    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define CA29    
     0 "MEME JOUR"
     1 "JOUR SUIVANT"
     2 "2 JOURS APRES LE DEBUT DE LA FIEVRE"
     3 "3 JOURS OU PLUS APRES LE DEBUT DE LA FIEVRE"
     8 "NSP"
     9 "NON REPONSE"
;
label define AN9     
     1 "YES"
     2 "NO, THE CHILD COULD NOT BE UNDRESSED TO THE MINIMUM"
     9 "NO RESPONSE"
;
label define AN12    
     1 "COUCHE"
     2 "DEBOUT"
     9 "NON REPONS"
;
label define AN14    
     1 "OUI"
     2 "Non"
;

#delimit cr
label values uf7m     UF7M    
label values uf9      UF9     
label values uf10     UF10    
label values uf17     UF17    
label values uf8h     UF8H    
label values uf8m     UF8M    
label values uf11h    UF11H   
label values uf11m    UF11M   
label values uf12     UF12    
label values uf13     UF13    
label values uf14     UF14    
label values uf15     UF15    
label values ub1d     UB1D    
label values ub1m     UB1M    
label values ub1y     UB1Y    
label values ub6      UB6     
label values ub7      UB7     
label values ub8      UB8     
label values ub9      UB9     
label values br1      BR1     
label values br2      BR2     
label values br3      BR3     
label values bd2      BD2     
label values bd3      BD3     
label values bd4      BD4     
label values bd5      BD5     
label values bd6      BD6     
label values bd7a     BD7A    
label values bd7b     BD7B    
label values bd7c     BD7C    
label values bd7d     BD7D    
label values bd7d1    BD7D1   
label values bd7e     BD7E    
label values bd7e1    BD7E1   
label values bd7x     BD7X    
label values bd8a     BD8A    
label values bd8a1    BD8A1   
label values bd8b     BD8B    
label values bd8c     BD8C    
label values bd8d     BD8D    
label values bd8e     BD8E    
label values bd8f     BD8F    
label values bd8g     BD8G    
label values bd8h     BD8H    
label values bd8i     BD8I    
label values bd8j     BD8J    
label values bd8k     BD8K    
label values bd8l     BD8L    
label values bd8m     BD8M    
label values bd8n     BD8N    
label values bd8o     BD8O    
label values bd8x     BD8X    
label values bd9      BD9     
label values bd8dummy BD8DUMMY
label values im2      IM2     
label values im3      IM3     
label values im5      IM5     
label values im6bd    IM6BD   
label values im6bm    IM6BM   
label values im6by    IM6BY   
label values im6p0d   IM6P0D  
label values im6p0m   IM6P0M  
label values im6p0y   IM6P0Y  
label values im6p1d   IM6P1D  
label values im6p1m   IM6P1M  
label values im6p1y   IM6P1Y  
label values im6p2d   IM6P2D  
label values im6p2m   IM6P2M  
label values im6p2y   IM6P2Y  
label values im6p3d   IM6P3D  
label values im6p3m   IM6P3M  
label values im6p3y   IM6P3Y  
label values im6id    IM6ID   
label values im6im    IM6IM   
label values im6iy    IM6IY   
label values im6penta1d IM6PENTA1D
label values im6penta1m IM6PENTA1M
label values im6penta1y IM6PENTA1Y
label values im6penta2d IM6PENTA2D
label values im6penta2m IM6PENTA2M
label values im6penta2y IM6PENTA2Y
label values im6penta3d IM6PENTA3D
label values im6penta3m IM6PENTA3M
label values im6penta3y IM6PENTA3Y
label values im6pcv1d IM6PCV1D
label values im6pcv1m IM6PCV1M
label values im6pcv1y IM6PCV1Y
label values im6pcv2d IM6PCV2D
label values im6pcv2m IM6PCV2M
label values im6pcv2y IM6PCV2Y
label values im6pcv3d IM6PCV3D
label values im6pcv3m IM6PCV3M
label values im6pcv3y IM6PCV3Y
label values im6md    IM6MD   
label values im6mm    IM6MM   
label values im6my    IM6MY   
label values im6yd    IM6YD   
label values im6ym    IM6YM   
label values im6yy    IM6YY   
label values im8a     IM8A    
label values im8b     IM8B    
label values im9      IM9     
label values im11     IM11    
label values im12a    IM12A   
label values im12b    IM12B   
label values im14     IM14    
label values im16     IM16    
label values im17     IM17    
label values im18     IM18    
label values im19     IM19    
label values im20     IM20    
label values im21     IM21    
label values im22     IM22    
label values im23     IM23    
label values im26     IM26    
label values im27     IM27    
label values im28     IM28    
label values im29     IM29    
label values ca0a     CA0A    
label values ca0b     CA0B    
label values ca1      CA1     
label values ca3      CA3     
label values ca4      CA4     
label values ca5      CA5     
label values ca7a     CA7A    
label values ca7b     CA7B    
label values ca7c     CA7C    
label values ca7d     CA7D    
label values ca7e     CA7E    
label values ca7f     CA7F    
label values ca7g     CA7G    
label values ca7h     CA7H    
label values ca7i     CA7I    
label values ca7j     CA7J    
label values ca7k     CA7K    
label values ca12     CA12    
label values ca14     CA14    
label values ca15     CA15    
label values ca16     CA16    
label values ca17     CA17    
label values ca18     CA18    
label values ca20     CA20    
label values ca22     CA22    
label values ca29     CA29    
label values an8      AN8     
label values an9      AN9     
label values an11     AN11    
label values an12     AN12    
label values an14     AN14    
