infix using "C:\ENQBASE\SUIVICFCRTM\DBCONCAT\HHP.dct"

label variable hh1      "Numéro de grappe"
label variable hh2      "Numéro du ménage"
label variable hh3      "Numéro Enquêteur"
label variable hh4      "Numéro Superviseur"
label variable hh5      "Date d'interview"
label variable hh5d     "Jour d'interview"
label variable hh5m     "Mois d'interview"
label variable hh5y     "Année d'interview"
label variable hhname   "Nom du chef de ménage"
label variable hh11     "Temps début de l' interview"
label variable hh11h    "Début de l' interview - Heure"
label variable hh11m    "Début de l'interview - Minutes"
label variable hh12     "Consentement"
label variable hh46     "Résultat de l'enquête"
label variable hh13     "Temps de fin de l'interview"
label variable hh13h    "Fin  de l'interview - Heure"
label variable hh13m    "Fin de l'nterview - Minutes"
label variable hh14     "Langage du  Questionnaire"
label variable hh15     "Langage de l'Interview"
label variable hh16     "Langue maternelle du répondant"
label variable hh17     "Besoin d’un traducteur pour n’importe quelle partie de ce questionnaire"
label variable hh33     "Consentement pour les filles de 15 - 17 ans interviewées"
label variable hh47     "Numéro du repondant au questionnaire Ménage"
label variable hh48     "Nombre de membres de ménage"
label variable hh49     "Nombre de femmes de 15 - 49 ans"
label variable hh53     "Nombre de questionnaires femmes completés"
label variable hh51     "Nombre d'enfants de moins de 5 ans"
label variable hh55     "Nombre de questionnaires des enfants de moins de 5 ans complétés"
label variable introhl  "Introduction à la Liste des membres du ménage"
label variable hhfin    "Fin"
label variable hh66     "Ville"
label variable hh67     "Zone de santé"
label variable hh68     "Aire de santé"
label variable hh69     "Village"
label variable hc3      "Nombre de pièces que les membres de ce ménage utilisent  habituellement pour drm"
label variable hc4      "Matériau principal du sol du logement"
label variable hc5      "Matériau principal du toit"
label variable hc6      "Matériau principal des murs extérieurs"
label variable hc7a     "Le ménage a : Une ligne de téléphone fixe"
label variable hc7b     "Le ménage a: Radio"
label variable hc7c     "Le ménage a: lampe à pétrole"
label variable hc7d     "Le ménage a: Horloge"
label variable hc7e     "Le ménage a: Lit"
label variable hc7f     "Le ménage a: Table"
label variable hc7g     "Le ménage a: Chaise"
label variable hc7h     "Le ménage a: Canapé"
label variable hc7i     "Le ménage a: Armoire"
label variable hc8      "L'électricité dans le ménage"
label variable hc9a     "Le ménage a: Television"
label variable hc9b     "Le ménage a: Refrigerateur"
label variable hc9c     "Le ménage a: cuisinière/ récaud"
label variable hc9d     "Le ménage a: Machine à laver"
label variable hc9e     "Le ménage a: Fer à répasser"
label variable hc9f     "Le ménage a:Ventilateur"
label variable hc9g     "Le ménage a: Chauffe eau"
label variable hc9h     "Le ménage a: Four micro-onde"
label variable hc9i     "Le ménage a: Lecteur DVD"
label variable hc9j     "Le ménage a: Climatiseur"
label variable hc10a    "Un membre de votre ménage possède :Une montre"
label variable hc10b    "Un membre de votre ménage possède:Une bicyclette/ vélo"
label variable hc10c    "Un membre de votre ménage possède:Une mobylette/ moto ou un scooter"
label variable hc10d    "Un membre de votre ménage possède:Une charrette tirée par un animal"
label variable hc10e    "Un membre de votre ménage possède:Une voiture, un camion ou une camionnette"
label variable hc10f    "Un membre de votre ménage possède:Un bateau à moteur"
label variable hc10g    "Un membre de votre ménage possède:Une pirogue ou une baleinière à moteur"
label variable hc10h    "Un membre de votre ménage possède:Une pirogue à pagaie"
label variable hc11     "Un membre du ménage a un ordinateur"
label variable hc12     "Un membre du ménage a un téléphone mobile"
label variable hc13     "Accès à Internet à la maison"
label variable hc14     "Le ménage est propriétaire du logement"
label variable hc15     "Un membre du ménage possède de la terre  qui peut être utilisée pour l'agricultu"
label variable hc16     "Nombre d'hectares des terres agricoles que les membres du ménage possèdent"
label variable hc17     "Le ménage possède-t-il des du bétail,des troupeaux et d'autres animaux de ferme "
label variable hc18a    "Le ménage possède: Vaches laitières ou taureaux"
label variable hc18b    "Le ménage possède: Autre gros bétail"
label variable hc18c    "Le ménage possède: Chevaux, ânes ou mules"
label variable hc18d    "Le ménage possède: Chèvres"
label variable hc18e    "Le ménage possède: Moutons"
label variable hc18f    "Le ménage possède: Volaille"
label variable hc18g    "Le ménage possède: Cochons"
label variable hc18h    "Le ménage possède: Lapins"
label variable hc18i    "Le ménage possède: Cobayes (cochons d’Inde)"
label variable hc19     "Est-ce que'un membre de ce ménage à un compte en banque"
label variable tn1      "Le ménage a le moustiquaire"
label variable tn2      "Nombre de moustiquaires a le ménage"
label variable ws1      "Source principale d'eau de boisson"
label variable ws2      "Priciopale source d'eau utilisée pour d'autres besoins (si l'eau de bouteille es"
label variable ws7      "Moments où le ménage n'a pas eu la quatité suffisante d'eau à boire , le mois de"
label variable ws11     "Type de topilettes utilisé par les membres de ménage"
label variable ws12     "Les fosses septiques ont déjà été vidées"
label variable ws13     "Lieu où le contenu des toilettes ont été mises"
label variable ws14     "L'emplacement/situation des toilettes"
label variable ws15     "Toilettes partagées avec avec des personnes qui ne sont membres du ménage"
label variable ws16     "Toilettes partagées avec d'autres ménages ou toilettes publiques"
label variable ws17     "Nombre de ménages qui partagent ces toilettes"
label variable hw1      "L'endroit où les membres du ménage se lavent habituellement les mains"
label variable hw2      "Présence d'eau au lieu de lavage des mains"
label variable hw3      "Savon ou détergent présent à l'endoit de lavage des mains"
label variable hw4      "Endoit habituel pour le lavage des mains"
label variable hw5      "Savon / autre matériel disponible pour le lavage des mains"
label variable hw6      "Matériel de lavage des mains observé"
label variable hw7      "Savon / autre matériel présent à l'endroit de lavage des mains"
label variable hw7a     "Barre de savon"
label variable hw7b     "Détergent (Poudre / Liquide / Pate)"
label variable hw7d     "Cendre"
label variable hw7e     "Boue/Terre/sable"
label variable hw7nr    "Manquant"
label variable hw99     "Commentaire ou Observation"

#delimit ;
label define HH12    
     1 "OUI, PERMISSION DONNEE"
     2 "NON, PERMISSION PAS DONNEE"
;
label define HH46    
     1 "COMPLETE"
     2 "PAS DE MEMBRE DU MENAGE A LA MAISON OU PAS DE REPONDANT DU MENAGE COMPETENT A LA MAISON AU MOMENT DE LA VISITE"
     3 "MENAGE ENTIER ABSENT POUR UNE LONGUE PERIODE DE TEMPS"
     4 "REFUS"
     5 "LOGEMENT VIDE OU ADRESSE N’EST PAS CELLE D’UN LOGEMENT"
     6 "LOGEMENT DETRUIT"
     7 "LOGEMENT PAS TROUVE"
    96 "AUTRE"
;
label define HH14    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define HH15    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define HH16    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
;
label define HH17    
     1 "OUI, QUESTIONNAIRE ENTIER"
     2 "OUI, PARTIES DU QUESTIONNAIRE"
     3 "NON, PAS BESOIN"
;
label define HH33    
     1 "OUI pour toutes les filles de 15-17 ans"
     2 "NON pour au moins une fille de 15-17 ans et ‘OUI’ pour au moins une fille de 15-17 ans"
     3 "NON pour toutes les filles de 15-17ans"
     4 "Aucune fille de 15-17 ans"
;
label define HHFIN   
     1 "Revisiter le questionnaire"
     2 "Ajouter les  notes"
     3 "Savegarder questionnaire et terminer"
;
label define HH66    
     1 "Kinshasa"
     2 "Kwango"
     3 "Ituri"
     4 "Kasaï Oriental"
;
label define HH67    
    11 "NSELE"
;
label define HC4     
    11 "TERRE / NATURE"
    12 "BOUSE"
    21 "PLANCHES DE BOIS"
    22 "PALME / BAMBOU"
    31 "PARQUET EN BOIS OU BOIS POLI"
    32 "VINYL OU BANDES D’ALSPHATE"
    33 "CARREAUX"
    34 "CIMENT"
    35 "MOQUETTE / TAPIS"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define HC5     
    11 "PAS DE TOIT"
    12 "CHAUME / FEUILLE DE PALME"
    13 "HERBES"
    21 "NATTE"
    22 "PALMIER / BAMBOU"
    23 "PLANCHES EN BOIS"
    24 "CARTON"
    31 "METAL / ALUMINIUM/ TOLE"
    32 "BOIS"
    33 "CALAMINE / FIBRE DE CIMENT"
    34 "TUILES"
    35 "CIMENT"
    36 "TOIT DE BARDEAUX (SHINGLES)"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define HC6     
    11 "PAS DE MURS"
    12 "CANE / PALME / TRONCS"
    13 "BOUE"
    21 "BAMBOU AVEC BOUE"
    22 "PIERRE AVEC BOUE"
    23 "ADOBE NON RECOUVERT/BANCO"
    24 "CONTRE PLAQUE"
    25 "CARTON"
    26 "BOIS RECYCLE"
    27 "TOLE"
    31 "CIMENT"
    32 "PIERRE AVEC CHAUX / CIMENT"
    33 "BRIQUES"
    34 "BLOCS DE CIMENT"
    35 "ADOBE/BANCO RECOUVERT"
    36 "PLANCHES DE BOIS/BARDEAUX"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define HC7A    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7B    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7C    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7D    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7E    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7F    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7G    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7H    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC7I    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC8     
     1 "OUI, CONNECTE AU SYSTEME GENERAL"
     2 "OUI, EN DEHORS DU SYSTEME (GENERATEUR/SYSTEME ISOLE)"
     3 "NON"
     9 "NON REPONSE"
;
label define HC9A    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9B    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9C    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9D    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9E    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9F    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9G    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9H    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9I    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC9J    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10A   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10B   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10C   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10D   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10E   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10F   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10G   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC10H   
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC11    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC12    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC13    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC14    
     1 "PROPRIETAIRE"
     2 "LOCATAIRE"
     3 "LOGE PAR LA FAMILLE"
     6 "AUTRE"
     9 "NON REPONSE"
;
label define HC15    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC16    
    95 "95 OU PLUS"
    98 "NSP"
    99 "NON REPONSE"
;
label define HC17    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HC18A   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18B   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18C   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18D   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18E   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18F   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18G   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18H   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC18I   
    95 "95+"
    98 "NSP"
    99 "NO RESPONSE"
;
label define HC19    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define TN1     
     1 "Oui"
     2 "Non"
;
label define WS1     
    11 "ROBINET: DANS LE LOGEMENT"
    12 "ROBINET: DANS LA CONCESSION/JARDIN/ PARCELLE"
    13 "ROBINET: CHEZ LE VOISIN"
    14 "ROBINET: ROBIENT PUBLIC/BORNE FONTAINE"
    21 "PUITS A POMPE/FORAGE"
    31 "PUITS CREUSE: PROTEGE"
    32 "PUITS CREUSE: NON PROTEGE"
    41 "SOURCE: SOURCE PROTEGEE"
    42 "SOURCE: SOURCE NON PROTEGEE"
    51 "EAU DE PLUIE"
    61 "CAMION CITERNE"
    62 "BIDON, BASSIN,SEAU LIVRE A DOMICILE"
    72 "KIOSQUE A EAU"
    81 "EAU DE SURFACE (RIVIERE, BARRAGE, LAC, MARE, COURANT, CANAL, SYSTEME D’IRRIGATION)"
    91 "EAU CONDITIONNEE: EAU EN BOUTEILLE"
    92 "EAU CONDITIONNEE: EAU EN SACHET"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define WS2     
    11 "ROBINET: DANS LE LOGEMENT"
    12 "ROBINET: DANS LA CONCESSION/JARDIN/ PARCELLE"
    13 "ROBINET: CHEZ LE VOISIN"
    14 "ROBINET: ROBIENT PUBLIC/BORNE FONTAINE"
    21 "PUITS A POMPE/FORAGE"
    31 "PUITS CREUSE: PROTEGE"
    32 "PUITS CREUSE: NON PROTEGE"
    41 "SOURCE: SOURCE PROTEGEE"
    42 "SOURCE: SOURCE NON PROTEGEE"
    51 "EAU DE PLUIE"
    61 "CAMION CITERNE"
    62 "BIDON / BASSIN / SEAU LIVRE  A  DOMICILE"
    81 "EAU DE SURFACE (RIVIERE, BARRAGE, LAC, MARE, COURANT, CANAL, SYSTEME D’IRRIGATION)"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define WS7     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
;
label define WS11    
    11 "CHASSE D’EAU RELIEE A SYSTEME D’EGOUTS"
    12 "CHASSE D’EAU RELIEE A FOSSE SEPTIQUE"
    13 "CHASSE D’EAU: RELIEE AUX LATRINES"
    14 "CHASSE D’EAU: RELIEE A L’AIR LIBRE"
    18 "CHASSE D’EAU: RELIEE A UN LIEU INCONNU"
    21 "LATRINE A FOSSE: AMELIOREE VENTILEE"
    22 "LATRINE A FOSSE: AVEC DALLE"
    23 "LATRINE A FOSSE: SANS DALLE/ FOSSE OUVERTE"
    31 "TOILETTE A COMPOSTAGE"
    41 "SEAU"
    51 "TOILETTES SUSPENDUES/LATRINES SUSPENDUES"
    95 "PAS DE TOILETTES/ NATURE/CHAMPS"
    96 "AUTRE"
    99 "NON REPONSE"
;
label define WS12    
     1 "OUI, VIDEES: DANS LES 5 DERNIERES ANNEES"
     2 "OUI, VIDEES: IL Y A PLUS DE 5 ANS"
     3 "OUI, VIDEES: NSP QUAND"
     4 "NON, JAMAIS VIDEES"
     8 "NSP"
     9 "NON REPONSE"
;
label define WS13    
     1 "ENLEVE PAR UN PRESTATAIRE DE SERVICE: DANS UNE USINE DE TRAITEMENT"
     2 "ENLEVE PAR UN PRESTATAIRE DE SERVICE: ENTERRE DANS UNE FOSSE COUVERTE"
     3 "ENLEVE PAR UN PRESTATAIRE DE SERVICE: NE SAIT PAS OU"
     4 "VIDEES PAR LE MENAGE: ENTERRE DANS UNE FOSSE COUVERTE"
     5 "VIDEES PAR LE MENAGE: DANS UNE FOSSE NON COUVERTE/ A L’AIR LIBRE/ JETE A L’EAU OU AILLEURS"
     6 "AUTRES"
     8 "NPS"
     9 "NON REPONSE"
;
label define WS14    
     1 "DANS LE LOGEMENT MEME"
     2 "DANS LEUR JARDIN/PARCELLE"
     3 "AILLEURS"
     9 "NON REPONSE"
;
label define WS15    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define WS16    
     1 "PARTAGEES AVEC MENAGES CONNUS (PAS PUBLIQUES)"
     2 "TOILETTES PUBLIQUES"
     9 "NON REPONSE"
;
label define WS17    
     2 "Deux"
     3 "Trois"
     4 "Quatre"
     5 "Cinq"
     6 "Six"
     7 "Sept"
     8 "Huit"
     9 "Neuf"
    10 "DIX MENAGES OU PLUS"
    98 "NSP"
    99 "NON REPONSE"
;
label define HW1     
     1 "OBSERVE: LIEU FIXE OBSERVE (LAVABO/ROBINET) DANS LE LOGEMENT"
     2 "OBSERVE: DANS LE JARDIN/PARCELLE"
     3 "OBSERVE: USTENSILE MOBILE OBSERVE (SEAU/ JARRE/ BOUILLOIRE)"
     4 "PAS OBSERVE: PAS DE LIEU DE LAVAGE DES MAINS DANS LE LOGEMENT/JARDIN/PARCELLE"
     5 "PAS OBSERVE: PAS DE PERMISSION DE VOIR"
     6 "AUTRE RAISON"
;
label define HW2     
     1 "EAU EST DISPONIBLE"
     2 "EAU N’EST PAS DISPONIBLE"
     9 "NON REPONSE"
;
label define HW3     
     1 "OUI, PRESENT"
     2 "NON, PAS PRESENT"
     9 "NON REPONSE"
;
label define HW4     
     1 "LIEU FIXE (LAVABO/ROBINET) DANS LE LOGEMENT"
     2 " DANS LA CONCESSION/PARCELLE"
     3 "OBJET MOBILE OBSERVE (SEAU / JARRE / BOUILLOIRE)"
     4 "PAS DE LIEU DE LAVAGE DES MAINS DANS LE LOGEMENT / JARDIN / PARCELLE"
     6 "AUTRE"
     9 "NON REPONSE"
;
label define HW5     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
;
label define HW6     
     1 "OUI, MONTRE"
     2 "NON, PAS MONTRE"
     9 "NON REPONSE"
;
label define HW99    
     1 "Oui"
     2 "Non"
;

#delimit cr
label values hh12     HH12    
label values hh46     HH46    
label values hh14     HH14    
label values hh15     HH15    
label values hh16     HH16    
label values hh17     HH17    
label values hh33     HH33    
label values hhfin    HHFIN   
label values hh66     HH66    
label values hh67     HH67    
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7a     HC7A    
label values hc7b     HC7B    
label values hc7c     HC7C    
label values hc7d     HC7D    
label values hc7e     HC7E    
label values hc7f     HC7F    
label values hc7g     HC7G    
label values hc7h     HC7H    
label values hc7i     HC7I    
label values hc8      HC8     
label values hc9a     HC9A    
label values hc9b     HC9B    
label values hc9c     HC9C    
label values hc9d     HC9D    
label values hc9e     HC9E    
label values hc9f     HC9F    
label values hc9g     HC9G    
label values hc9h     HC9H    
label values hc9i     HC9I    
label values hc9j     HC9J    
label values hc10a    HC10A   
label values hc10b    HC10B   
label values hc10c    HC10C   
label values hc10d    HC10D   
label values hc10e    HC10E   
label values hc10f    HC10F   
label values hc10g    HC10G   
label values hc10h    HC10H   
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc14     HC14    
label values hc15     HC15    
label values hc16     HC16    
label values hc17     HC17    
label values hc18a    HC18A   
label values hc18b    HC18B   
label values hc18c    HC18C   
label values hc18d    HC18D   
label values hc18e    HC18E   
label values hc18f    HC18F   
label values hc18g    HC18G   
label values hc18h    HC18H   
label values hc18i    HC18I   
label values hc19     HC19    
label values tn1      TN1     
label values ws1      WS1     
label values ws2      WS2     
label values ws7      WS7     
label values ws11     WS11    
label values ws12     WS12    
label values ws13     WS13    
label values ws14     WS14    
label values ws15     WS15    
label values ws16     WS16    
label values ws17     WS17    
label values hw1      HW1     
label values hw2      HW2     
label values hw3      HW3     
label values hw4      HW4     
label values hw5      HW5     
label values hw6      HW6     
label values hw99     HW99    
