DATA LIST FILE='C:\ENQBASE\SUIVICFCRTM\DBCONCAT\WMDB' RECORDS=1
 /
 WM1         1-2   
 WM2         3-4   
 WM3         5-6   
 WM3A        7-86   (A)
 WM4        87-87  
 WM5        88-89  
 WM6        90-97  
 WM6D       98-99  
 WM6M      100-101 
 WM6Y      102-105 
 WM8       106-106 
 WM9       107-107 
 WM17      108-109 
 WM7       110-113 
 WM7H      114-115 
 WM7M      116-117 
 WM10      118-121 
 WM10H     122-123 
 WM10M     124-125 
 WM11      126-126 
 WM12      127-127 
 WM13      128-128 
 WM14      129-129 
 WM15      130-130 
 WMHINT    131-132 
 WB3       133-138 
 WB3M      139-140 
 WB3Y      141-144 
 WB4       145-146 
 WB5       147-147 
 WB6A      148-149 
 WB6B      150-151 
 WB7       152-152 
 WB9       153-153 
 WB10A     154-155 
 WB10B     156-157 
 WB11      158-158 
 WB12A     159-160 
 WB12B     161-162 
 WB14      163-163 
 WB18      164-164 
 WB19      165-188  (A)
 WB19A     189-192  (A)
 WB19B     193-196  (A)
 WB19C     197-200  (A)
 WB19D     201-204  (A)
 WB19X     205-208  (A)
 WB19NR    209-212  (A)
 WDOI      213-216 
 WB1C      217-220 
 WB1F      221-221 
 WB2C      222-223 
 WAGE      224-224 
 WB3C      225-228 
 WB3F      229-229 
 WB4C      230-231 
 CM1       232-232 
 CM8       233-233 
 CM15C     234-239 
 CM15CM    240-241 
 CM15CY    242-245 
 CM18      246-325  (A)
 CM17      326-326 
 CM18A     327-328 
 MN1A      329-329 
 MN1B      330-330 
 MN2       331-331 
 MN3       332-359  (A)
 MN3A      360-363  (A)
 MN3C      364-367  (A)
 MN3D      368-371  (A)
 MN3F      372-375  (A)
 MN3G      376-379  (A)
 MN3X      380-383  (A)
 MN3NR     384-387  (A)
 MN4U      388-388 
 MN4N      389-390 
 MN5       391-392 
 MN6A      393-393 
 MN6B      394-394 
 MN6C      395-395 
 MN7       396-396 
 MN8       397-397 
 MN9       398-398 
 MN11      399-399 
 MN12      400-400 
 MN14      401-402 
 MN16      403-403 
 MN17      404-405 
 MN18      406-421  (A)
 MN18A     422-425  (A)
 MN18B     426-429  (A)
 MN18X     430-433  (A)
 MN18NR    434-437  (A)
 MN19      438-473  (A)
 MN19A     474-477  (A)
 MN19C     478-481  (A)
 MN19D     482-485  (A)
 MN19F     486-489  (A)
 MN19G     490-493  (A)
 MN19H     494-497  (A)
 MN19X     498-501  (A)
 MN19Y     502-505  (A)
 MN19NR    506-509  (A)
 MN20      510-511 
 MN21      512-512 
 MN22      513-513 
 MN23      514-514 
 MN24      515-515 
 MN25      516-516 
 MN26      517-519 
 MN26U     520-520 
 MN26N     521-522 
 MN28      523-523 
 MN29      524-524 
 MN30      525-525 
 MN31      526-557  (A)
 MN31A     558-561  (A)
 MN31B     562-565  (A)
 MN31C     566-569  (A)
 MN31D     570-573  (A)
 MN31E     574-577  (A)
 MN31X     578-581  (A)
 MN31Z     582-585  (A)
 MN31NR    586-589  (A)
 MN32      590-590 
 MN33      591-591 
 MN34A     592-592 
 MN34      593-597  (3)
 MN35      598-598 
 MN36      599-599 
 MN37      600-602 
 MN37U     603-603 
 MN37N     604-605 
 MN38      606-606 
 MN39      607-658  (A)
 MN39A     659-662  (A)
 MN39B     663-666  (A)
 MN39C     667-670  (A)
 MN39D     671-674  (A)
 MN39E     675-678  (A)
 MN39F     679-682  (A)
 MN39G     683-686  (A)
 MN39H     687-690  (A)
 MN39I     691-694  (A)
 MN39J     695-698  (A)
 MN39X     699-702  (A)
 MN39Y     703-706  (A)
 MN39NR    707-710  (A)
 PN3       711-713 
 PN3U      714-714 
 PN3N      715-716 
 PN4       717-717 
 PN5       718-718 
 PN6       719-719 
 PN8       720-720 
 PN9       721-721 
 PN10      722-722 
 PN11      723-723 
 PN12      724-724 
 PN13      725-727 
 PN13U     728-728 
 PN13N     729-730 
 PN14      731-762  (A)
 PN14A     763-766  (A)
 PN14C     767-770  (A)
 PN14D     771-774  (A)
 PN14F     775-778  (A)
 PN14G     779-782  (A)
 PN14H     783-786  (A)
 PN14X     787-790  (A)
 PN14NR    791-794  (A)
 PN15      795-796 
 PN17      797-797 
 PN19      798-798 
 PN20      799-799 
 PN21      800-800 
 PN22      801-803 
 PN22U     804-804 
 PN22N     805-806 
 PN23      807-838  (A)
 PN23A     839-842  (A)
 PN23C     843-846  (A)
 PN23D     847-850  (A)
 PN23F     851-854  (A)
 PN23G     855-858  (A)
 PN23H     859-862  (A)
 PN23X     863-866  (A)
 PN23NR    867-870  (A)
 PN24      871-872 
 PN25A     873-873 
 PN25B     874-874 
 PN25C     875-875 
 PN27      876-876 
 PN29      877-877 
 PN30      878-878 
 MA1       879-879 
 MA5       880-880 
 MA6       881-881 
 MA7       882-882 
 MA8       883-888 
 MA8M      889-890 
 MA8Y      891-894 
 TEF5      895-895 
 CAS1      896-896 
 CAS2      897-940  (A)
 CAS2A     941-944  (A)
 CAS2B     945-948  (A)
 CAS2C     949-952  (A)
 CAS2D     953-956  (A)
 CAS2E     957-960  (A)
 CAS2F     961-964  (A)
 CAS2G     965-968  (A)
 CAS2H     969-972  (A)
 CAS2I     973-976  (A)
 CAS2X     977-980  (A)
 CAS2Z     981-984  (A)
 CAS3      985-985 
 CAS4      986-987 
 AC1       988-988 
 AC2       989-989 
 AC3       990-1013 (A)
 AC3A     1014-1017 (A)
 AC3B     1018-1021 (A)
 AC3C     1022-1025 (A)
 AC3D     1026-1029 (A)
 AC3X     1030-1033 (A)
 AC3Z     1034-1037 (A)
 AC4      1038-1039
 AC5      1040-1041
 AC6      1042-1069 (A)
 AC6A     1070-1073 (A)
 AC6B     1074-1077 (A)
 AC6C     1078-1081 (A)
 AC6D     1082-1085 (A)
 AC6E     1086-1089 (A)
 AC6X     1090-1093 (A)
 AC6Z     1094-1097 (A)
 DC1      1098-1117 (A)
 DC1A     1118-1121 (A)
 DC1B     1122-1125 (A)
 DC1C     1126-1129 (A)
 DC1X     1130-1133 (A)
 DC1Z     1134-1137 (A)
 DC2      1138-1138
 BR1      1139-1139
 BR2      1140-1140
 BR3      1141-1141
 BR4      1142-1177 (A)
 BR4A     1178-1181 (A)
 BR4B     1182-1185 (A)
 BR4C     1186-1189 (A)
 BR4D     1190-1193 (A)
 BR4E     1194-1197 (A)
 BR4F     1198-1201 (A)
 BR4G     1202-1205 (A)
 BR4X     1206-1209 (A)
 BR4Z     1210-1213 (A)
 BR5      1214-1229 (A)
 BR5A     1230-1233 (A)
 BR5B     1234-1237 (A)
 BR5X     1238-1241 (A)
 BR5Z     1242-1245 (A)
 BR6      1246-1246
 BR7      1247-1294 (A)
 BR7A     1295-1298 (A)
 BR7B     1299-1302 (A)
 BR7C     1303-1306 (A)
 BR7D     1307-1310 (A)
 BR7E     1311-1314 (A)
 BR7F     1315-1318 (A)
 BR7G     1319-1322 (A)
 BR7H     1323-1326 (A)
 BR7I     1327-1330 (A)
 BR7J     1331-1334 (A)
 BR7X     1335-1338 (A)
 BR7Z     1339-1342 (A)
 IM1      1343-1343
 IM2      1344-1344
 IM3      1345-1372 (A)
 IM3A     1373-1376 (A)
 IM3B     1377-1380 (A)
 IM3C     1381-1384 (A)
 IM3D     1385-1388 (A)
 IM3E     1389-1392 (A)
 IM3X     1393-1396 (A)
 IM3Z     1397-1400 (A)
 IM4      1401-1468 (A)
 IM4A     1469-1472 (A)
 IM4B     1473-1476 (A)
 IM4C     1477-1480 (A)
 IM4D     1481-1484 (A)
 IM4E     1485-1488 (A)
 IM4F     1489-1492 (A)
 IM4G     1493-1496 (A)
 IM4H     1497-1500 (A)
 IM4I     1501-1504 (A)
 IM4J     1505-1508 (A)
 IM4K     1509-1512 (A)
 IM4L     1513-1516 (A)
 IM4M     1517-1520 (A)
 IM4N     1521-1524 (A)
 IM4O     1525-1528 (A)
 IM4X     1529-1532 (A)
 IM4Z     1533-1536 (A)
 IM5      1537-1537
 IM6      1538-1577 (A)
 IM6A     1578-1581 (A)
 IM6B     1582-1585 (A)
 IM6C     1586-1589 (A)
 IM6D     1590-1593 (A)
 IM6E     1594-1597 (A)
 IM6F     1598-1601 (A)
 IM6G     1602-1605 (A)
 IM6H     1606-1609 (A)
 IM6X     1610-1613 (A)
 IM6Z     1614-1617 (A)
 IM7      1618-1677 (A)
 IM7A     1678-1681 (A)
 IM7B     1682-1685 (A)
 IM7C     1686-1689 (A)
 IM7D     1690-1693 (A)
 IM7E     1694-1697 (A)
 IM7F     1698-1701 (A)
 IM7G     1702-1705 (A)
 IM7H     1706-1709 (A)
 IM7I     1710-1713 (A)
 IM7J     1714-1717 (A)
 IM7K     1718-1721 (A)
 IM7M     1722-1725 (A)
 IM7N     1726-1729 (A)
 IM7X     1730-1733 (A)
 IM7Z     1734-1737 (A)
 IM8      1738-1757 (A)
 IM8A     1758-1761 (A)
 IM8B     1762-1765 (A)
 IM8C     1766-1769 (A)
 IM8X     1770-1773 (A)
 IM8Z     1774-1777 (A)
 IM9      1778-1801 (A)
 IM9A     1802-1805 (A)
 IM9B     1806-1809 (A)
 IM9C     1810-1813 (A)
 IM9D     1814-1817 (A)
 IM9X     1818-1821 (A)
 IM9Z     1822-1825 (A)
 IM10     1826-1829
 IM10U    1830-1830
 IM10N    1831-1832
 VIT1     1833-1833
 VIT2     1834-1834
 VIT3     1835-1862 (A)
 VIT3A    1863-1866 (A)
 VIT3B    1867-1870 (A)
 VIT3C    1871-1874 (A)
 VIT3D    1875-1878 (A)
 VIT3E    1879-1882 (A)
 VIT3X    1883-1886 (A)
 VIT3Z    1887-1890 (A)
 VIT4     1891-1892
 VIT5     1893-1894
 VIT6     1895-1914 (A)
 VIT6A    1915-1918 (A)
 VIT6B    1919-1922 (A)
 VIT6C    1923-1926 (A)
 VIT6X    1927-1930 (A)
 VIT6Z    1931-1934 (A)
 DEW1     1935-1935
 DEW2     1936-1936
 DEW3     1937-1960 (A)
 DEW3A    1961-1964 (A)
 DEW3B    1965-1968 (A)
 DEW3C    1969-1972 (A)
 DEW3D    1973-1976 (A)
 DEW3X    1977-1980 (A)
 DEW3Z    1981-1984 (A)
 DEW4     1985-1986
 DEW5     1987-1987
 DEW6     1988-1988
 DEW7     1989-2012 (A)
 DEW7A    2013-2016 (A)
 DEW7B    2017-2020 (A)
 DEW7C    2021-2024 (A)
 DEW7D    2025-2028 (A)
 DEW7X    2029-2032 (A)
 DEW7Z    2033-2036 (A)
 SAN1     2037-2038
 SAN2     2039-2039
 SAN3     2040-2040
 SAN4     2041-2076 (A)
 SAN4A    2077-2080 (A)
 SAN4B    2081-2084 (A)
 SAN4C    2085-2088 (A)
 SAN4D    2089-2092 (A)
 SAN4E    2093-2096 (A)
 SAN4F    2097-2100 (A)
 SAN4G    2101-2104 (A)
 SAN4X    2105-2108 (A)
 SAN4Z    2109-2112 (A)
 SAN5     2113-2113
 HD1      2114-2114
 HD2      2115-2138 (A)
 HD2A     2139-2142 (A)
 HD2B     2143-2146 (A)
 HD2C     2147-2150 (A)
 HD2D     2151-2154 (A)
 HD2X     2155-2158 (A)
 HD2Z     2159-2162 (A)
 HD3      2163-2194 (A)
 HD3A     2195-2198 (A)
 HD3B     2199-2202 (A)
 HD3C     2203-2206 (A)
 HD3D     2207-2210 (A)
 HD3E     2211-2214 (A)
 HD3F     2215-2218 (A)
 HD3X     2219-2222 (A)
 HD3Z     2223-2226 (A)
 HD4      2227-2227
.
VARIABLE LABELS
  WM1      "Numero de grappe"
 /WM2      "Numéro de ménage"
 /WM3      "Numéro de ligne de la mère"
 /WM3A     "Nom  de la femme"
 /WM4      "Numéro du Superviseur"
 /WM5      "Code de l'enquêtrice"
 /WM6      "Date de l'interview"
 /WM6D     "Jour de l'interview"
 /WM6M     "Mois de l'interview"
 /WM6Y     "Année de l'interview"
 /WM8      "Répondant du ménage"
 /WM9      "Consentement"
 /WM17     "Résultat de l'interview de la femme"
 /WM7      "Temps du début de l'interview"
 /WM7H     "Début de l'interview - Heure"
 /WM7M     "Début de l'interview - Minutes"
 /WM10     "Temps de la fin de l'interview"
 /WM10H    "Fin de l'interview - Heure"
 /WM10M    "Fin de l'interview - Minutes"
 /WM11     "Interview teminée en privé"
 /WM12     "Langue du Questionnaire"
 /WM13     "Lange de l'Interview"
 /WM14     "Langue maternel du répondant"
 /WM15     "Usage du traducteur"
 /WMHINT   "intervieweur du menage"
 /WB3      "Date de naissance de la femme"
 /WB3M     "Mois de naissance de la femme"
 /WB3Y     "Année de naissance de la femme"
 /WB4      "Age de la femme"
 /WB5      "Déjà fréquenté l'école"
 /WB6A     "Le plus haut niveau d'école fréquenté"
 /WB6B     "La classe la plus élevéé fréquentée à ce niveau"
 /WB7      "Classe completée"
 /WB9      "Fréquentation à l'école pendant l'année scolaire en cours (2018-2019)"
 /WB10A    "Niveau fréquienté  pendant l'année scolaire actuelle (2018-2019)"
 /WB10B    "Classe fréquentée pendant l'année scolaire actuelle (2018 - 2019)"
 /WB11     "A fréquenter l'école l'année dernière (2017 - 2018)"
 /WB12A    "Niveau d'école fréquenté l'année  dernière (2017-2018)"
 /WB12B    "Classe fréquentée l'année dernière (2017-2018)"
 /WB14     "Peut lire une partie de la phrase"
 /WB18     "Couvert par l'assurance maladie"
 /WB19     "Type d'assurance maladie"
 /WB19A    "Type d'assurance maladie:  Organisation mutuelle de santé/Assurance santé à base communautaire"
 /WB19B    "Type d'assurance maladie: Assurance santé de l'employeur"
 /WB19C    "Type d'assurance maladie: Sécurité sociale"
 /WB19D    "Type d'assurance maladie: Autre assurance santé& priv&ée achetée"
 /WB19X    "Type d'assurance maladie:Autre"
 /WB19NR   "Type d'assurance maladie: Non réponse"
 /WDOI     "Date d'entretien femmes (CMC)"
 /WB1C     "Date de naissance de la femme (CMC)"
 /WB1F     "Indicateur de date pour WB1"
 /WB2C     "Age de la répondante (calculé)"
 /WAGE     "Age"
 /WB3C     "Date de naissance de la femme (CMC)"
 /WB3F     "Indicateur de date pour WB3"
 /WB4C     "Computed age of respondent"
 /CM1      "A-t-elle déjà donné naissance"
 /CM8      "A-t-elle déjà eu un enfant né vivant et qui est mort plus tard"
 /CM15C    "Date de naissance de votre (dernier) né même si il/elle est décédé"
 /CM15CM   "Mois de naissance"
 /CM15CY   "Année de naissance"
 /CM18     "Nom de la dernière naissance"
 /CM17     "Naissances vivantes dans les 2 dernières années"
 /CM18A    "code de la naissance au cours de 2 dernières années"
 /MN1A     "Avez-vous reçu le kit d'accouchement lors de votre grossesse de (nom)"
 /MN1B     "Avez-vous utilisé votre kit d'accouchement pour l'accouchement de (nom)"
 /MN2      "A reçu les soins prénataux"
 /MN3      "Fournisseur de soins prénataux"
 /MN3A     "Fournisseur de soins prénataux:  Médecin"
 /MN3C     "Fournisseur de soins prénataux:  Infirmière/ Infirmière"
 /MN3D     "Fournisseur de soins prénataux:  Accoucheuse/ sage femme"
 /MN3F     "Fournisseur de soins prénataux: Accoucheuse traditionnelle"
 /MN3G     "Fournisseur de soins prénataux: Agent de santé communautaire"
 /MN3X     "Fournisseur de soins prénataux: Autre"
 /MN3NR    "Fournisseur de soins prénataux: Non réponse"
 /MN4U     "Semaines ou mois de grossesse au premier soin prénatal - Unité"
 /MN4N     "Semaines ou mois de grossesse au premier soin prénatal - Nombre"
 /MN5      "Nombre de fois en consultation prénatale"
 /MN6A     "Tension"
 /MN6B     "Echantillon d'urine"
 /MN6C     "Echantillon de sang"
 /MN7      "Possède une carte de vaccination"
 /MN8      "Injection antitétanique pendant la dernière grossesse"
 /MN9      "Nombre de fois l'injection antitétanique  a été reçue au cours de la dernière grossesse"
 /MN11     "Injection d'antitétanique avant la dernière grossesse"
 /MN12     "Nombre de fois l'injection antitétanique  a été reçue avant la dernière grossesse"
 /MN14     "Cela fait combien d'années a été reçu cette injection antitétanique"
 /MN16     "Prise de SP/Fansidar durant la grossesse"
 /MN17     "Nombre de fois que le SP/Fansidar a été pris durant la dernière grossesse"
 /MN18     "Reçu SP / Fansidar lors d'une visite de soins prénatals ou lors d'une autre visite"
 /MN18A    "Reçu SP / Fansidar lors d'une visite de soins prénatals, ou lors d'une autre visite: Visite parentale"
 /MN18B    "Reçu SP / Fansidar lors d'une visite de soins prénatals ou lors d'une autre visite: Visite dans un Centre de santé"
 /MN18X    "Reçu SP / Fansidar lors d'une visite de soins prénatals, ou lors d'une autre visite: Autre source"
 /MN18NR   "Reçu SP / Fansidar lors d'une visite de soins prénatals, ou lors d'une autre visite:Non réponse"
 /MN19     "Assistance à l'accouchement"
 /MN19A    "Assistance à l'accouchement: MEDECIN"
 /MN19C    "Assistance à l'accouchement: INFIRMIER/INFIRMIERE"
 /MN19D    "Assistance à l'accouchement: ACCOUCHEUSE/SAGE-FEMME"
 /MN19F    "Assistance à l'accouchement: ACCOUCHEUSE TRADITIONNELLE/MATRONE"
 /MN19G    "Assistance à l'accouchement: AGENT DE SANTE COMMUNAUTAIRE"
 /MN19H    "Assistance à l'accouchement: PARENT/AMI"
 /MN19X    "Assistance à l'accouchement: AUTRE"
 /MN19Y    "Assistance à l'accouchement: PERSONNE"
 /MN19NR   "Assistance à l'accouchement: NON REPONSE"
 /MN20     "Lieu d'accouchemnt"
 /MN21     "Accouchemnt par césarienne"
 /MN22     "Quand la décision d'accoucher par césarienne a été prise"
 /MN23     "Après la naissance, le bébé a été placé directement sur la peau nue de la poitrine de la mère"
 /MN24     "Bébé a été enveloppé avant d'être placé sur la poitrine de la mère"
 /MN25     "Le bébé a été séché(e) ou essuyé(e) peu de temps après la naissance"
 /MN26     "Temps que le bébé  a été lavé après la naissance"
 /MN26U    "Temps que le bébé  a été lavé après la naissance - Unité"
 /MN26N    "Temps que le bébé  a été lavé après la naissance - Nombre"
 /MN28     "Ce qui a été utilisé pour couper le cordon"
 /MN29     "Instrument utilisé pour couper le cordon  a été bouilli avant l'utilisation"
 /MN30     "Quelque chose a été appliquée sur le cordon ombilical après avoir été coupé"
 /MN31     "Ce qui a été appliqué au cordon"
 /MN31A    "Ce qui a été appliqué au cordon:  Chlorhexidine/Betadine"
 /MN31B    "Ce qui a été appliqué au cordon:  Autre antiseptique (alcool, cordial gentiale violette)"
 /MN31C    "Ce qui a été appliqué au cordon:  Huile de palme"
 /MN31D    "Ce qui a été appliqué au cordon:  Cendre"
 /MN31E    "Ce qui a été appliqué au cordon: Bouses d'animaux"
 /MN31X    "Ce qui a été appliqué au cordon: Autre"
 /MN31Z    "Ce qui a été appliqué au cordon: NSP / Ne se souvient pas"
 /MN31NR   "Ce qui a été appliqué au cordon: Non réponse"
 /MN32     "Taille de l'enfant à la naissance"
 /MN33     "Pesé à la naissance"
 /MN34A    "Poids enregistré sur le certificat de naissance ou déclaration de la mère"
 /MN34     "Poids à la naissance (kilogrammes)"
 /MN35     "Retour des règles depuis la naissance de l'enfant"
 /MN36     "Avez-vous déjà allaité"
 /MN37     "Temps  ap^rès la naissance que ler bébé a été mis au sein"
 /MN37U    "Temps  ap^rès la naissance que ler bébé a été mis au sein - Unité"
 /MN37N    "Temps  ap^rès la naissance que ler bébé a été mis au sein - Nombre"
 /MN38     "Dans les 3 premiers jours après l'accouchement, l'enfant a reçu quelque chose à boire que le lait maternel"
 /MN39     "Enfant a reçu à boire"
 /MN39A    "Enfant a reçu à boire:  Lait (autre que maternel)"
 /MN39B    "Enfant a reçu à boire: De l'eau seule"
 /MN39C    "Enfant a reçu à boire: Sucre à eau avc du glucose"
 /MN39D    "Enfant a reçu à boire: Calmant pour colique"
 /MN39E    "Enfant a reçu à boire: Solution Eau -Salée-sucrée"
 /MN39F    "Enfant a reçu à boire: Jus de fruit"
 /MN39G    "Enfant a reçu à boire:Lait maternisé"
 /MN39H    "Enfant a reçu à boire: Thé / Infusions / Préparations"
 /MN39I    "Enfant a reçu à boire: Miel"
 /MN39J    "Enfant a reçu à boire: Médicaments prescrrits"
 /MN39X    "Enfant a reçu à boire: Autre"
 /MN39Y    "Enfant a reçu à boire: Rien donné à boire"
 /MN39NR   "Enfant a reçu à boire: Non réponse"
 /PN3      "Temps resté au Centre de santé après l'accouchement"
 /PN3U     "Temps resté au Centre de santé après l'accouchement- Unité"
 /PN3N     "Temps resté au Centre de santé après l'accouchement - Nombre"
 /PN4      "Quelqu'un a examiné l'état de santé de bébé avant de quitter le Centre de santé"
 /PN5      "L'état de santé de la mère vérifiée avant de quitter le Centre de santé"
 /PN6      "Quelqu'un a examiné l'état de santé de bébé après avoir quitté le Centre de santé"
 /PN8      "Etat der santé dubébé vérifié à la fin de l'accouchement"
 /PN9      "Etat de santé de la mère vérifié  à la fin de l'accouchement"
 /PN10     "Vérification supplémentaire de l'état de santé apès l'accouchement"
 /PN11     "Etat de santé du bébé vérifié après l'accouchement"
 /PN12     "Nombre de fois que le bébé a été examiné"
 /PN13     "Nombre de fois que la mère a été examiné après la naissance du bébé"
 /PN13U    "Combien de temps après l'accouchement a eu le premier contrôle du bébé - Unité"
 /PN13N    "Combien de temps après l'accouchement a eu le premier contrôle du bébé - Nombre"
 /PN14     "Assistance du bébé à l'accouchement"
 /PN14A    "Assistance du bébé à l'accouchement: MEDECIN"
 /PN14C    "Assistance du bébé à l'accouchement: INFIRMIER/INFIRMIERE"
 /PN14D    "Assistance du bébé à l'accouchement: ACCOUCHEUSE/SAGE-FEMME"
 /PN14F    "Assistance du bébé à l'accouchement: ACCOUCHEUSE TRADITIONNELLE/MATRONE"
 /PN14G    "Assistance du bébé à l'accouchement: AGENT DE SANTE COMMUNAUTAIRE"
 /PN14H    "Assistance du bébé à l'accouchement: PARENT/AMI"
 /PN14X    "Assistance du bébé à l'accouchement: AUTRE"
 /PN14NR   "Assistance du bébé à l'accouchement: NON REPONSE"
 /PN15     "L'endroit où la santé du bébé a été examimée"
 /PN17     "Etat de la mère vérifié après avoir quitté la structure de santé"
 /PN19     "Etat de santé de la mère vérifié  à la fin de l'accouchement"
 /PN20     "Etat de santé de la mère vérifié  après la naissance du bébé"
 /PN21     "Nombre de fois que la mère a été examiné après la naissance du bébé"
 /PN22     "Combien de temps après l'accouchement a eu le premier contrôle de la mère"
 /PN22U    "Combien de temps après l'accouchement a eu le premier contrôle de la mère - Unité"
 /PN22N    "Combien de temps après l'accouchement a eu le premier contrôle de la mère- Nombre"
 /PN23     "Assistance de la mère à l'accouchement"
 /PN23A    "Assistance de la mère à l'accouchement: MEDECIN"
 /PN23C    "Assistance de la mère à l'accouchement: INFIRMIER/INFIRMIERE"
 /PN23D    "Assistance de la mère à l'accouchement: ACCOUCHEUSE/SAGE-FEMME"
 /PN23F    "Assistance de la mère à l'accouchement: ACCOUCHEUSE TRADITIONNELLE/MATRONE"
 /PN23G    "Assistance à l'accouchement: AGENT DE SANTE COMMUNAUTAIRE"
 /PN23H    "Assistance de la mère à l'accouchement: PARENT/AMI"
 /PN23X    "Assistance de la mère à l'accouchement: AUTRE"
 /PN23NR   "Assistance de la mère à l'accouchement: NON REPONSE"
 /PN24     "L'endroit où la santé e la mère a été examinée"
 /PN25A    "Durant les deux premiers jours après la naissance, un agent  de santé a fait des actes suivants:  Examiner le  cordon"
 /PN25B    "Durant les deux premiers jours après la naissance, un agent  de santé a fait des actes suivants: Prendre la temperature"
 /PN25C    "Durant les deux premiers jours après la naissance, un agent  de santé a fait des actes suivants: Counseils surl'allaitement"
 /PN27     "Durant les deux premiers jours après la naissance, un agent  de santé observe l'allaitement"
 /PN29     "Durant les deux premiers jours après la naissance, un agent  de santé  a pesé de nouveau l'enfant"
 /PN30     "Durant les deux premiers jours après la naissance, un agent  de santé a donné des informations sur les symptômes de la maladie del'enfant"
 /MA1      "Actuellement marié ou vivant avec un homme"
 /MA5      "Déjà été mariée ou vécu avec quelqu'un comme mariée"
 /MA6      "Situation matrimoniale actuelle"
 /MA7      "Déjà été mariée ou vécu avec quelqu'un une fois ou plus d'une fois"
 /MA8      "Date de la première union"
 /MA8M     "Mois de la première union"
 /MA8Y     "Année de la première union"
 /TEF5     "Est-ce que la maman a un  enfant de moins 3 ans ?"
 /CAS1     "Est-il difficile ou pas difficile pour vous de rechercher des soins dans un établissement de santé pour vous même ou pour vos enfants ?"
 /CAS2     "pourquoi c’est difficile pour vous de rechercher des soins dans un établissement de santé pour vous même ou pour vos enfants?"
 /CAS2A    "FRAIS DE TRANSPORT ELEVES POUR MOI.................."
 /CAS2B    "ETABLISSEMENT EST LOIN / DIFFICILE D’ACCES"
 /CAS2C    "Frais des services de soins trop élevés pour moi"
 /CAS2D    "CHARGE DE LA GARDE D'ENFANTS"
 /CAS2E    "CHARGE DU TRAVAIL (INTERIEUR / EXTERIEUR MAISON)"
 /CAS2F    "MARI / PARTENAIRE N’AUTORISE PAS"
 /CAS2G    "PERSONNEL DE L'ETABLISSEMENT INSOLENT"
 /CAS2H    "PAS DE PERSONNEL FEMININ  DANS L’ETABLISSMENT"
 /CAS2I    "LONGUE ATTENTE DANS LES LOCAUX"
 /CAS2X    "AUTRE (préciser)"
 /CAS2Z    "NSP/PAS SUR"
 /CAS3     "pouvez compter sur les agents de santé communautaire en termes de préventions ou de traitements des maladies ?"
 /CAS4     "À quelle fréquence recevez-vous la visite d'un agent de santé communautaire (ACS) ?"
 /AC1      "Pensez-vous que pouvez compter sur les agents de santé communautaire en termes de préventions ou de traitements des maladies ?"
 /AC2      "les soins prénatals sont-ils importants pour les femmes enceintes ?"
 /AC3      "Pourquoi pensez-vous que les soins prénatals sont importants pour les femmes enceintes?"
 /AC3A     "AVOIR UNE GROSSESSE SAINE"
 /AC3B     "APPRENDRE A PREVENIR LES RISQUES POUR LA MAMAN ET LE BEBE"
 /AC3C     "OBTENIR DES MOUSTIQUAIRES ET DES VITAMINES"
 /AC3D     "COMPRENDRE COMMENT / OU DONNER NAISSANCE"
 /AC3X     "AUTRE"
 /AC3Z     "NSP/PAS SURE"
 /AC4      "A quel âge de la grossesse pensez-vous qu'une femme enceinte devrait avoir sa première visite de soins prénatals ?"
 /AC5      "Combien de visites prénatales pensez-vous sont nécessaires pendant la grossesse avant l’accouchement ?"
 /AC6      "Pourquoi pensez-vous que les soins prénatals ne sont pas importants pour les femmes enceintes?"
 /AC6A     "MERE SAIT QUOI FAIRE"
 /AC6B     "PARENT PEUT FOURNIR DES CONSEILS"
 /AC6C     "PAS DE BESOIN SI LA FEMME A DEJA MIS AU MONDE"
 /AC6D     "AUCUN RISQUE"
 /AC6E     "CROYANCES RELIGIEUSES ET CULTURELLES"
 /AC6X     "AUTRE"
 /AC6Z     "NSP/PAS SURE"
 /DC1      "Qui pensez-vous devrait assister les femmes lors de l’accouchement de leur bébé ?"
 /DC1A     "PERSONNEL DE SANTE (MEDECIN,INFIRMIERE,SAGE-FEMME)"
 /DC1B     "ACCOUCHEUSETRADITIONNELLE / ACCOUCHEUSE COMMUNAUTAIRE"
 /DC1C     "PARENTE / AMIE"
 /DC1X     "AUTRE"
 /DC1Z     "NSP/PAS SURE"
 /DC2      "À votre avis, quel est le lieu le plus sûr pour les femmes pour accoucher leur bébé ?"
 /BR1      "Avez-vous déjà entendu parler de l'enregistrement de la naissance auprès des autorités civiles?"
 /BR2      "Est-ce que quelqu'un vous a déjà dit comment enregistrer la naissance de votre enfant"
 /BR3      "À votre avis, est-il important d'enregistrer la naissance d'un bébé auprès des autorités civiles ?"
 /BR4      "Pourquoi pensez-vous qu'il est important d'enregistrer la naissance d'un enfant ?"
 /BR4A     "ACCÈS AUX SERVICES DE SANTÉ"
 /BR4B     "ACCÈS À L’ÉDUCATION"
 /BR4C     "AVOIR UNE IDENTITÉ JURIDIQUE"
 /BR4D     "AVOIR UN DOCUMENT"
 /BR4E     "DONNER UN NOM OFFICIEL"
 /BR4F     "DONNEZ-LA CITOYENNETÉ/ NATIONALITE"
 /BR4G     "POUR POUVOIR VOYAGER"
 /BR4X     "AUTRE (préciser"
 /BR4Z     "NSP /PAS SÛRE"
 /BR5      "Pourquoi pensez-vous qu'il n’est pas important d’enregistrer la naissance d'un enfant ?"
 /BR5A     "NE FAIT AUCUNE DIFFERENCE"
 /BR5B     "A DEJA UN NOM"
 /BR5X     "AUTRE (préciser"
 /BR5Z     "NSP / PAS SURE"
 /BR6      "Selon votre expérience, est-il difficile d'enregistrer la naissance d'un enfant ?"
 /BR7      "Qu'est-ce qui a rendu difficile l'enregistrement de la naissance de votre enfant ?"
 /BR7A     "NE SAIT PAS QUE C’EST UN REQUIS LÉGAL"
 /BR7B     "PAS ASSEZ D'ARGENT"
 /BR7C     "DISTANCE"
 /BR7D     "PROCESSUS TROP LONG /COMPLEXE"
 /BR7E     "DOCUMENTS INCOMPLETS"
 /BR7F     "PÈRE ABSENT"
 /BR7G     "L'ENFANT N'A PAS ENCORE UN NOM"
 /BR7H     "PARLER DIFFÉRENTES LANGUES"
 /BR7I     "MANQUE D'ALPHABETISATION"
 /BR7J     "JE NE SAIS PAS COMMENT INSCRIRE"
 /BR7X     "AUTRE (préciser"
 /BR7Z     "NE SAIT PAS / PAS SURE"
 /IM1      "Avez-vous déjà entendu parler de la vaccination des enfants ?"
 /IM2      "À votre avis, la vaccination est-elle importante pour les enfants ?"
 /IM3      "À votre avis, pourquoi est-il important de vacciner les enfants ?"
 /IM3A     "PREVENIR UNE MALADIE"
 /IM3B     "PRÉVENIR LA MORT"
 /IM3C     "RESTER SAIN"
 /IM3D     "BIEN SE DEVELOPPER"
 /IM3E     "POUR CONSTRUIRE SYSTEME IMMUNITAIRE"
 /IM3X     "AUTRE (PRECISER)"
 /IM3Z     "NSP/PAS SURE"
 /IM4      "La vaccination est faite pour empêcher certaines maladies.Pouvez-vous me dire quelles sont les maladies qui peuvent être prévenues par la vaccination ?"
 /IM4A     "POLIOMYELITE"
 /IM4B     "ROUGEOLE"
 /IM4C     "DIPHTERIE"
 /IM4D     "PERTUSSIS (COQUELUCHE)"
 /IM4E     "RUBEOLE (ROUGEOLE ALLEMANDE)"
 /IM4F     "OREILLONS"
 /IM4G     "TETANOS"
 /IM4H     "ROTAVIRUS / DIARRHEE"
 /IM4I     "HAEMOPHILUS INFLUENZAE DE TYPE B"
 /IM4J     "TUBERCULOSE"
 /IM4K     "TYPHOÏDE"
 /IM4L     "HEPATITE"
 /IM4M     "FIEVRE JAUNE"
 /IM4N     "VIH / SIDA"
 /IM4O     "PALUDISME"
 /IM4X     "AUTRE (préciser)"
 /IM4Z     "NE SAIT PAS / PAS SURE"
 /IM5      "Selon vous, combien de contacts avec les services de santé sont nécessaires pour qu'un enfant reçoive tous les vaccins requis?"
 /IM6      "Selon vous, à quels âges l'enfant doit-il être emmené à un centre de sante/ clinique mobile pour la vaccination ?"
 /IM6A     "A LA NAISSANCE"
 /IM6B     "6 SEMAINES"
 /IM6C     "10 SEMAINES"
 /IM6D     "14 SEMAINES"
 /IM6E     "9 MOIS"
 /IM6F     "15-18 MOIS"
 /IM6G     "CAMPAGNES"
 /IM6H     "TOUS LES MOIS AU COURS DE LA PREMIÈRE ANNÉE"
 /IM6X     "AUTRE (préciser)"
 /IM6Z     "NSP/PAS SURE"
 /IM7      "Certains enfants pourraient rater certains vaccins au moment idéal pour une raison quelconque. Selon vous quelles peuvent être ces raisons ?"
 /IM7A     "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE LE VACCIN"
 /IM7B     "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE 2E OU 3E DOSE"
 /IM7C     "ENFANT N’EST PAS A L’AISE"
 /IM7D     "PEUR DES EFFETS SECONDAIRES"
 /IM7E     "MERE TROP OCCUPEE"
 /IM7F     "LE MOMENT POUR LE VACCIN N’EST PAS CONVENABLE"
 /IM7G     "MERE N’EST PAS A L’AISE"
 /IM7H     "PAS D'ARGENT POUR PAYER LES CHARGES"
 /IM7I     "LIEU DE VACCINATION TROP LOIN ET PAS D’ARGENT SUFFISANT POUR PAYER LE TRANSPORT"
 /IM7J     "AUCUN VACCIN DISPONIBLE"
 /IM7K     "AUCUN PERSONNEL DE LA SANTE DISPONIBLE"
 /IM7M     "PARENTS PEUVENT OUBLIER"
 /IM7N     "CENTRE DEBORDE DE PATIENTS/LONGUE ATTENTE"
 /IM7X     "AUTRE(préciser"
 /IM7Z     "NSP/PAS SURE"
 /IM8      "Pourquoi la vaccination n’est pas importante pour les enfants ?"
 /IM8A     "EFFETS SECONDAIRES"
 /IM8B     "ENFANTS PEUVENT TOMBER MALADES"
 /IM8C     "RAISONS RELIGIEUSES"
 /IM8X     "AUTRE (préciser)"
 /IM8Z     "NSP/PAS SURE"
 /IM9      "Selon vous, où est ce que les enfants se font vacciner dans votre voisinage ?"
 /IM9A     "ETABLISSEMENT DE SANTE  / CLINIQUE"
 /IM9B     "CENTRES DE VACCINATION DE PROXIMITE"
 /IM9C     "CLINIQUE MOBILE"
 /IM9D     "PENDANT LES CAMPAGNES DE VACCINATION"
 /IM9X     "AUTRE (préciser"
 /IM9Z     "NSP/PAS SURE"
 /IM10     "Combien du temps faut-il pour se rendre dans le centre de santé le plus proche ?"
 /IM10U    "Combien du temps faut-il pour se rendre dans le centre de santé le plus proche ?/UNITE"
 /IM10N    "Combien du temps faut-il pour se rendre dans le centre de santé le plus proche ?/NOMBRE"
 /VIT1     "Avez-vous déjà entendu parler de supplémentation en vitamine A pour les enfants"
 /VIT2     "À votre avis, est-il important que les enfants reçoivent la vitamine A ?"
 /VIT3     "Pourquoi pensez-vous qu'il est important que les enfants reçoivent la vitamine A ?"
 /VIT3A    "ÉVITER LES MALADIES"
 /VIT3B    "ÉVITER LA MORT"
 /VIT3C    "RESTER EN BONNE SANTE"
 /VIT3D    "TRAITEMENT D’UNE MALADIE"
 /VIT3E    "DEVELOPPER L’IMMUNITÉ"
 /VIT3X    "AUTRE (Préciser)"
 /VIT3Z    "NSP/PAS SURE"
 /VIT4     "A quel âge pensez-vous qu’un enfant devrait commencer à recevoir des suppléments de vitamine A ?"
 /VIT5     "Jusqu'à quel âge pensez-vous qu'un enfant doit recevoir des supplémentations en vitamine A ?"
 /VIT6     "Pourquoi pensez-vous que ce n'est pas important que les enfants reçoivent la vitamine A ?"
 /VIT6A    "CE N’EST PAS NÉCESSAIRE"
 /VIT6B    "ENFANT MANGE BIEN"
 /VIT6C    "CROYANCE RELIGIEUSE"
 /VIT6X    "AUTRE (préciser)"
 /VIT6Z    "NSP/PAS SURE"
 /DEW1     "Avez-vous déjà entendu parler du déparasitage ?"
 /DEW2     "À votre avis, est-il important ou non de déparasiter les enfants ?"
 /DEW3     "Pourquoi pensez-vous qu'il est important de donner des vermifuges aux enfants ?"
 /DEW3A    "TUER LES PARASITES /ELIMINER LES VERS"
 /DEW3B    "PRÉVENIR LES MALADIES"
 /DEW3C    "LES AIDER À RESTER EN SANTÉ"
 /DEW3D    "REMEDE DE LA MALADIE"
 /DEW3X    "AUTRE (préciser)"
 /DEW3Z    "NSP/PAS SURE"
 /DEW4     "A quel âge pensez-vous qu'un enfant devrait commencer à recevoir des médicaments vermifuges ?"
 /DEW5     "À quelle fréquence pensez-vous qu'un enfant doit recevoir des médicaments vermifuge s?"
 /DEW6     "Jusqu'à quel âge pensez-vous qu'un enfant doit recevoir des médicaments vermifuges ?"
 /DEW7     "Pourquoi pensez-vous qu'il n’est pas important de déparasiter les enfants ?"
 /DEW7A    "NÉCESSAIRE"
 /DEW7B    "IL N’Y A PAS DE VERS AUTOUR"
 /DEW7C    "ENFANT N’EST PAS EXPOSE / PAS DE CONTACT AVEC LE TERRAIN........."
 /DEW7D    "CROYANCE RELIGIEUSE"
 /DEW7X    "AUTRE (préciser"
 /DEW7Z    "NSP/PAS SURE"
 /SAN1     "À votre avis, quelles sont les méthodes sûres d'élimination des excréments, y compris les matières fécales des enfants ?"
 /SAN2     "Lorsque les membres de la communauté n’ont pas d’endroit sûr et disponible pour faire leurs besoins"
 /SAN3     "Quel est le problème majeur de la défécation à l’air libre pour la communauté ?"
 /SAN4     "Quelles maladies pensez-vous que les gens de la communauté peuvent avoir du fait de la défécation en plein air dans la communauté ?"
 /SAN4A    "PALUDISME"
 /SAN4B    "TUBERCULOSE"
 /SAN4C    "FIEVRE TYPHOÏDE"
 /SAN4D    "FIEVRE JAUNE"
 /SAN4E    "CHOLERA"
 /SAN4F    "DIARRHÉE"
 /SAN4G    "DYSENTERIE"
 /SAN4X    "AUTRE (Préciser)"
 /SAN4Z    "NSP/PAS SURE"
 /SAN5     "À votre avis, est-il important que chaque ménage dispose de toilettes ou de latrines propres ?"
 /HD1      "Y a-t-il un avantage ou non à se laver les mains au savon régulièrement ?"
 /HD2      "Quels sont les principaux avantages de se laver les mains régulièrement avec du savon"
 /HD2A     "NETTOYER LA SALETE"
 /HD2B     "PRÉVENIR LES MALADIES OU LES INFECTIONS GERMINALES"
 /HD2C     "MAINS PROPRES / ELEGANCE"
 /HD2D     "PAIX DE L’ESPRIT"
 /HD2X     "AUTRE (préciser"
 /HD2Z     "NSP/PAS SURE"
 /HD3      "Selon vous, quels sont les moments les plus importants pour vous et les membres de votre famille, y compris les enfants, pour le lavage des mains ?"
 /HD3A     "AVANT REPAS"
 /HD3B     "AVANT DE NOURRIR UN ENFANT"
 /HD3C     "PRÉPARER / SERVIR UN REPAS"
 /HD3D     "APRÈS TOILETTES / LATRINES"
 /HD3E     "APRÈS LE NETTOYAGE DES FESSES D’UN ENFANT OU LE CHANGEMENT DE COUCHE"
 /HD3F     "APRÈS LES REPAS"
 /HD3X     "AUTRE (préciser"
 /HD3Z     "NSP/PAS SURE"
 /HD4      "Est-il pratique, pour vous et les autres membres de votre ménage, de se laver les mains régulièrement avec du savon ?"
.
VALUE LABELS
  WM6M    
     1 "janvier"
     2 "février"
     3 "mars"
     4 "avril"
     5 "mai"
     6 "juin"
     7 "juillet"
     8 "août"
     9 "septembre"
    10 "octobre"
    11 "novembre"
    12 "décembre"
 /WM8     
     1 "OUI, DEJA INTERVIEWEE"
     2 "NON, PREMIERE INTERVIEW"
 /WM9     
     1 "OUI, PERMISSION EST DONNEE"
     2 "NON, PERMISSION N’EST PAS DONNEE"
 /WM17    
     1 "COMPLETE"
     2 "PAS A LA MAISON"
     3 "REFUSE"
     4 "PARTIELLEMENT COMPLETE"
     5 "EN INCAPACITE"
     6 "PAS DE CONSENTEMENT D’UN ADULTE POUR CETTE REPONDANTE DE 15-17 ANS"
    96 "Autre"
 /WM7H    
    99 "NON REPONSE"
 /WM7M    
    99 "NON REPONSE"
 /WM10H   
    99 "NON REPONSE"
 /WM10M   
    99 "NON REPONSE"
 /WM11    
     1 "OUI, L’ENTRETIEN ENTIER S’EST DEROULE EN PRIVE"
     2 "NON, D’AUTRES ETAIENT PRESENTS DURANT TOUT L’ENTRETIEN"
     3 "NON, D’AUTRES ETAIENT PRESENTS UNE PARTIE DE L’ENTRETIEN"
 /WM12    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
 /WM13    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
 /WM14    
     1 "FRANÇAIS"
     2 "KIKONGO"
     3 "LINGALA"
     4 "SWAHILI"
     5 "TSHILUBA"
     6 "AUTRE LANGUE"
     9 "NON REPONSE"
 /WM15    
     1 "OUI, QUESTIONNAIRE ENTIER"
     2 "OUI, PARTIES DU QUESTIONNAIRE"
     3 "NON, PAS UTILISE"
 /WB3M    
     1 "JANVIER"
     2 "FÉVRIER"
     3 "MARS"
     4 "AVRIL"
     5 "MAI"
     6 "JUIN"
     7 "JUILLET"
     8 "AOUT"
     9 "SEPTEMBRE"
    10 "OCTOBRE"
    11 "NOVEMBRE"
    12 "DECEMBRE"
    98 "NSP"
    99 "NON REPONSE"
 /WB3Y    
  9998 "NSP"
  9999 "NON REPONSE"
 /WB5     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /WB6A    
     0 "PREPRIMAIRE"
    10 "PRIMAIRE"
    20 "SECONDAIRE 1"
    31 "SECONDAIRE 2 GENER"
    32 "SECONDAIRE 2 TECHN"
    33 "SECONDAIRE 2 PROFES"
    34 "SECONDAIRE 2 ART&M"
    40 "SUPERIEUR"
    98 "NSP"
    99 "NON REPONSE"
 /WB6B    
    98 "NSP"
    99 "NON REPONSE"
 /WB7     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /WB9     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /WB10A   
     0 "PREPRIMAIRE"
    10 "PRIMAIRE"
    20 "SECONDAIRE 1"
    31 "SECONDAIRE 2 GENER"
    32 "SECONDAIRE 2 TECHN"
    33 "SECONDAIRE 2 PROFES"
    34 "SECONDAIRE 2 ART&M"
    40 "SUPERIEUR"
    98 "NSP"
    99 "NON REPONSE"
 /WB10B   
    98 "NSP"
    99 "NON REPONSE"
 /WB11    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /WB12A   
     0 "PREPRIMAIRE"
    10 "PRIMAIRE"
    20 "SECONDAIRE 1"
    31 "SECONDAIRE 2 GENER"
    32 "SECONDAIRE 2 TECHN"
    33 "SECONDAIRE 2 PROFES"
    34 "SECONDAIRE 2 ART&M"
    40 "SUPERIEUR"
    98 "NSP"
    99 "NON REPONSE"
 /WB12B   
    98 "NSP"
    99 "NON REPONSE"
 /WB14    
     1 "NE PEUT PAS LIRE DU TOUT"
     2 "CAPABLE DE NE LIRE QUE QUELQUES PARTIES DE LA PHRASE"
     3 "CAPABLE  DE LIRE TOUTE LA PHRASE"
     6 "PAS DE PHRASE DANS LE LANGAGE REQUIS/ BRAILLE"
     9 "NON REPONSE"
 /WB18    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /WB19    
  'A     ' "ORGANISATION  MUTUELLE DE SANTE/ ASSURANCE SANTE A BASE COMMUNAUTAIRE"
  'B     ' "ASSURANCE SANTE DE L’EMPLOYEUR"
  'C     ' "SECURITE SOCIALE"
  'D     ' "AUTRE ASSURANCE SANTE PRIVEE ACHETEE"
  'X     ' "AUTRE"
  '?     ' "NON REPONSE"
 /WB19A   
  'A' "ORGANISATION  MUTUELLE DE SANTE/ ASSURANCE SANTE A BASE COMMUNAUTAIRE"
  '?' "NON REPONSE"
 /WB19B   
  'B' "ASSURANCE SANTE DE L’EMPLOYEUR"
  '?' "NON REPONSE"
 /WB19C   
  'C' "SECURITE SOCIALE"
  '?' "NON REPONSE"
 /WB19D   
  'D' "AUTRE ASSURANCE SANTE PRIVEE ACHETEE"
  '?' "NON REPONSE"
 /WB19X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /WB19NR  
  '?' "NON REPONSE"
 /WB1F    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
 /WAGE    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
 /WB3F    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
 /CM1     
     1 "OUI"
     2 "NON"
 /CM8     
     1 "OUI"
     2 "NON"
 /CM15CM  
     1 "JANVIER"
     2 "FÉVRIER"
     3 "MARS"
     4 "AVRIL"
     5 "MAI"
     6 "JUIN"
     7 "JUILLET"
     8 "AOUT"
     9 "SEPTEMBRE"
    10 "OCTOBRE"
    11 "NOVEMBRE"
    12 "DECEMBRE"
    98 "NSP"
    99 "NON REPONSE"
 /CM15CY  
  9998 "NSP"
 /CM17    
     0 "PAS DE NAISSNCES VIVANTES DANS LES 3 DERNIERES ANNEES"
     1 "UNE OU PLUS NAISSANCES VIVANTES DANS LES 3 DERNIERES ANNEES"
 /MN1A    
     1 "OUI"
     2 "NON"
     9 "NO REPONSE"
 /MN1B    
     1 "OUI"
     2 "NON"
     9 "NO REPONSE"
 /MN2     
     1 "OUI"
     2 "NON"
     9 "NO REPONSE"
 /MN3     
  'A      ' "MEDECIN"
  'C      ' "INFIRMIERE/INFIRMIER"
  'D      ' "ACOUCHEUSE/SAGE FEMME"
  'F      ' "ACCOUCHEUSE TRADITIONNELLE"
  'G      ' "AGENT DE SANTE COMMUNAUTAIRE"
  'X      ' "AUTRE"
  '?      ' "NON REPONSE"
 /MN3A    
  'A' "MEDECIN"
  '?' "NON REPONSE"
 /MN3C    
  'C' "INFIRMIERE/INFIRMIER"
  '?' "NON REPONSE"
 /MN3D    
  'D' "ACCOUCHEUSE/SAGE-FEMME"
  '?' "NON REPONSE"
 /MN3F    
  'F' "ACCOUCHEUSE TRADITIONNELLE"
  '?' "NON REPONSE"
 /MN3G    
  'G' "AGENT DE SANTE COMMUNAUTAIRE"
  '?' "NON REPONSE"
 /MN3X    
  'X' "AUTRE"
  '?' "NON REPONSE"
 /MN3NR   
  '?' "NON REPONSE"
 /MN4U    
     1 "SEMAINES"
     2 "MOIS"
     9 "SPECIAL"
 /MN4N    
    98 "NSP"
    99 "NON REPONSE"
 /MN5     
    98 "NSP"
    99 "NON REPONSE"
 /MN6A    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN6B    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN6C    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN7     
     1 "OUI (CARNET OU AUTRE DOCUMENT VU)"
     2 "OUI (CARNET OU AUTRE DOCUMENT PAS VU)"
     3 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /MN8     
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /MN9     
     1 "1  FOIS"
     2 "2 FOIS"
     3 "3 FOIS"
     4 "4 FOIS"
     5 "5  FOIS"
     6 "6 FOIS"
     7 "7 FOIS"
     8 "NSP"
 /MN11    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /MN12    
     7 "7+"
     8 "NSP"
     9 "NON REPONSE"
 /MN14    
    99 "NON REPONSE"
 /MN16    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /MN17    
    98 "NSP"
    99 "NON REPONSE"
 /MN18    
  'A   ' "VISITE PRENATALE"
  'B   ' "VISITE DANS UN AUTRE CENTRE DE SANTE"
  'X   ' "AUTRE SOURCE"
  '?   ' "NON REPONSE"
 /MN18A   
  'A' "VISITE PRENATALE"
  '?' "NON REPONSE"
 /MN18B   
  'B' "VISITE DANS UN AUTRE CENTRE DE SANTE"
  '?' "NON REPONSE"
 /MN18X   
  'X' "AUTRE SOURCE"
  '?' "NON REPONSE"
 /MN18NR  
  '?' "NON REPONSE"
 /MN19    
  'A        ' "MEDECIN"
  'C        ' "INFIRMIERE/INFIRMIER"
  'D        ' "ACOUCHEUSE/SAGE FEMME"
  'F        ' "ACCOUCHEUSE TRADITIONNELLE"
  'G        ' "AGENT DE SANTE COMMUNAUTAIRE"
  'H        ' "PARENT/AMI"
  'X        ' "AUTRE"
  'Y        ' "PERSONNE"
  '?        ' "NON REPONSE"
 /MN19A   
  'A' "MEDECIN"
  '?' "NON REPONSE"
 /MN19C   
  'C' "INFIRMIERE/INFIRMIER"
  '?' "NON REPONSE"
 /MN19D   
  'D' "ACCOUCHEUSE/SAGE-FEMME"
  '?' "NON REPONSE"
 /MN19F   
  'F' "ACCOUCHEUSE TRADITIONNELLE"
  '?' "NON REPONSE"
 /MN19G   
  'G' "AGENT DE SANTE COMMUNAUTAIRE"
  '?' "NON REPONSE"
 /MN19H   
  'H' "PARENT / AMI"
  '?' "NON REPONSE"
 /MN19X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /MN19Y   
  'Y' "PERSONNE"
  '?' "NON REPONSE"
 /MN19NR  
  '?' "NON REPONSE"
 /MN20    
    11 "DOMICILE DE L’ENQUETEE"
    12 "AUTRE DOMICILE"
    21 "HOPITAL GOUVERNEMENTAL"
    22 "CLINIQUE / CENTRE DE SANTE GOUV"
    23 "POSTE DE SANTE GOUVERNEMENTAL"
    26 "AUTRE PUBLIC"
    31 "HOPITAL PRIVE"
    32 "CLINIQUE PRIVEE"
    36 "MATERNITE PRIVEE"
    96 "AUTRE PRIVE MEDICAL"
    99 "NON REPONSE"
 /MN21    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN22    
     1 "AVANT LES DOULEURS DE L’ACCOUCHEMENT"
     2 "APRES LES DOULEURS DE L’ACCOUCHEMENT"
     9 "NON REPONSE"
 /MN23    
     1 "OUI"
     2 "NON"
     8 "NSP/ NE SE SOUVIENT PAS"
     9 "NON REPONSE"
 /MN24    
     1 "OUI"
     2 "NON"
     8 "NSP/ NE SE SOUVIENT PAS"
     9 "NON REPONSE"
 /MN25    
     1 "OUI"
     2 "NON"
     8 "NSP/ NE SE SOUVIENT PAS"
     9 "NON REPONSE"
 /MN26    
     0 "IMMEDIATEMENT"
   998 "NSP / NE SE SOUVIENT PAS"
   998 "NON REPONSE"
 /MN26U   
     0 "IMMEDIATEMENT"
     1 "HEURES"
     2 "JOURS"
     9 "JAMAIS LAVE/NSP / NE SE SOUVIENT PAS"
 /MN26N   
     0 "IMMEDIATEMENT"
    97 "JAMAIS LAVE"
    98 "NSP / NE SE SOUVIENT PAS"
    99 "NON REPONSE"
 /MN28    
     1 "LAME NEUVE"
     2 "LAME DEJA UTILISEE POUR AUTRES RAISONS"
     3 "CISEAUX"
     6 "AUTRE"
     8 "NSP"
     9 "NON REPONSE"
 /MN29    
     1 "OUI"
     2 "NON"
     8 "NSP / NE SE SOUVIENT PAS"
     9 "NON REPONSE"
 /MN30    
     1 "OUI"
     2 "NON"
     8 "NSP / NE SE SOUVIENT PAS"
     9 "NON REPONSE"
 /MN31    
  'A       ' "CHLORHEXIDINE/BETADINE"
  'B       ' "AUTRE ANTISEPTIQUE (ALCOOL,  CORDIAL, GENTIANE VIOLETTE)"
  'C       ' "HUILE DE MOUTARDE"
  'D       ' "CENDRE"
  'E       ' "BOUSES D’ANIMAUX"
  'X       ' "AUTRE"
  'Z       ' "NSP/ NE SE SOUVIENT PAS"
  '?       ' "NON REPONSE"
 /MN31A   
  'A' "CHLORHEXIDINE"
  '?' "NON REPONSE"
 /MN31B   
  'B' "AUTRE ANTISEPTIQUE (ALCOOL,  CORDIAL, GENTIANE VIOLETTE)"
  '?' "NON REPONSE"
 /MN31C   
  'C' "HUILE DE MOUTARDE"
  '?' "NON REPONSE"
 /MN31D   
  'D' "CENDRE"
  '?' "NON REPONSE"
 /MN31E   
  'E' "BOUSES D’ANIMAUX"
  '?' "NON REPONSE"
 /MN31X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /MN31Z   
  'Y' "NSP/ NE SE SOUVIENT PAS"
  '?' "NON REPONSE"
 /MN31NR  
  '?' "NON REPONSE"
 /MN32    
     1 "TRES GROS"
     2 "PLUS GROS QUE LA MOYENNE"
     3 "MOYEN"
     4 "PLUS PETIT QUE LA MOYENNE"
     5 "TRES PETIT"
     8 "NSP"
     9 "NON REPONSE"
 /MN33    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /MN34A   
     1 "OUI, DANS UN CERTIFICAT"
     2 "NON, DE MEMOIRE"
     8 "NSP"
     9 "NON REPONSE"
 /MN34    
  9,998 "NSP"
  9,999 "NON REPONSE"
 /MN35    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN36    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN37    
     0 "IMMEDIATEMENT"
   998 "NSP / NE SE SOUVIENT PAS"
   999 "NON REPONSE"
 /MN37U   
     0 "IMMEDIATEMENT"
     1 "HEURES"
     2 "JOURS"
     9 "SPECIAL"
 /MN37N   
     0 "IMMEDIATEMENT"
    98 "NSP / NE SE SOUVIENT PAS"
    99 "NON REPONSE"
 /MN38    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MN39    
  'A            ' "LAIT (AUTRE QUE MATERNEL)"
  'B            ' "DE L’EAU SEULE"
  'C            ' "SUCRE OU EAU AVEC DU GLUCOSE"
  'D            ' "EAU GRIPE"
  'E            ' "SOLUTION EAU-SALEE-SUCREE"
  'F            ' "JUS DE FRUIT"
  'G            ' "LAIT MATERNISE"
  'H            ' "THE / INFUSIONS / PREPARATIONS TRADITIONNELLES A BASE DE PLANTES"
  'I            ' "MIEL"
  'J            ' "MEDICAMENTS PRESCRITS"
  'X            ' "AUTRE"
  'Y            ' "RIEN DONNE A BOIRE"
  '?            ' "NON REPONSE"
 /MN39A   
  'A' "LAIT (AUTRE QUE MATERNEL)"
  '?' "NON REPONSE"
 /MN39B   
  'B' "DE L’EAU SEULE"
  '?' "NON REPONSE"
 /MN39C   
  'C' "SUCRE OU EAU AVEC DU GLUCOSE"
  '?' "NON REPONSE"
 /MN39D   
  'D' "EAU GRIPE"
  '?' "NON REPONSE"
 /MN39E   
  'E' "SOLUTION EAU-SALEE-SUCREE"
  '?' "NON REPONSE"
 /MN39F   
  'F' "JUS DE FRUIT"
  '?' "NON REPONSE"
 /MN39G   
  'G' "LAIT MATERNISE"
  '?' "NON REPONSE"
 /MN39H   
  'H' "THE / INFUSIONS / PREPARATIONS TRADITIONNELLES A BASE DE PLANTES"
  '?' "NON REPONSE"
 /MN39I   
  'I' "MIEL"
  '?' "NON REPONSE"
 /MN39J   
  'J' "MEDICAMENTS PRESCRITS"
  '?' "NON REPONSE"
 /MN39X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /MN39Y   
  'Y' "RIEN DONNE A BOIRE"
  '?' "NON REPONSE"
 /MN39NR  
  '?' "NON REPONSE"
 /PN3     
   998 "NSP / NE SE SOUVIENT PAS"
   999 "NON REPONSE"
 /PN3U    
     1 "HEURES"
     2 "JOURS"
     3 "SEMAINES"
     9 "SPECIAL"
 /PN3N    
    98 "NSP / NE SE SOUVIENT PAS"
    99 "NON REPONSE"
 /PN4     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN5     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN6     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN8     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN9     
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN10    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN11    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN12    
     1 "UNE FOIS"
     2 "PLUS D’UNE FOIS"
     9 "NON REPONSE"
 /PN13    
   998 "NSP / NE SE SOUVIENT PAS"
   999 "NON REPONSE"
 /PN13U   
     1 "HEURES"
     2 "JOURS"
     3 "SEMAINES"
     9 "SPECIAL"
 /PN13N   
    98 "NSP / NE SE SOUVIENT PAS"
    99 "NON REPONSE"
 /PN14    
  'A       ' "MEDECIN"
  'C       ' "INFIRMIERE/INFIRMIER"
  'D       ' "ACOUCHEUSE/SAGE FEMME"
  'F       ' "ACCOUCHEUSE TRADITIONNELLE"
  'G       ' "AGENT DE SANTE COMMUNAUTAIRE"
  'H       ' "PARENT/AMI"
  'X       ' "AUTRE"
  '?       ' "NON REPONSE"
 /PN14A   
  'A' "MEDECIN"
  '?' "NON REPONSE"
 /PN14C   
  'C' "INFIRMIERE/INFIRMIER"
  '?' "NON REPONSE"
 /PN14D   
  'D' "ACOUCHEUSE /  SAGE FEMME"
  '?' "NON REPONSE"
 /PN14F   
  'F' "ACCOUCHEUSE TRADITIONNELLE"
  '?' "NON REPONSE"
 /PN14G   
  'G' "AGENT DE SANTE COMMUNAUTAIRE"
  '?' "NON REPONSE"
 /PN14H   
  'H' "PARENT/AMI"
  '?' "NON REPONSE"
 /PN14X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /PN14NR  
  '?' "NON REPONSE"
 /PN15    
    11 "DOMICILE DE L’ENQUETEE"
    12 "AUTRE DOMICILE"
    21 "HOPITAL GOUVERNEMENTAL"
    22 "CLINIQUE / CENTRE DE SANTE GOUV"
    23 "POSTE DE SANTE GOUVERNEMENTAL"
    26 "AUTRE PUBLIC"
    31 "HOPITAL PRIVE"
    32 "CLINIQUE PRIVEE"
    36 "MATERNITE PRIVEE"
    96 "AUTRE PRIVATE MEDICAL"
    99 "NON REPONSE"
 /PN17    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN19    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN20    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN21    
     1 "UNE FOIS"
     2 "PLUS D’UNE FOIS"
     9 "NON REPONSE"
 /PN22    
   998 "NSP / NE SE SOUVIENT PAS"
   999 "NON REPONSE"
 /PN22U   
     1 "HEURES"
     2 "JOURS"
     3 "SEMAINES"
     9 "SPECIAL"
 /PN22N   
    98 "NSP / NE SE SOUVIENT PAS"
    99 "NON REPONSE"
 /PN23    
  'A       ' "MEDECIN"
  'C       ' "INFIRMIERE/INFIRMIER"
  'D       ' "ACOUCHEUSE/SAGE FEMME"
  'F       ' "ACCOUCHEUSE TRADITIONNELLE"
  'G       ' "AGENT DE SANTE COMMUNAUTAIRE"
  'H       ' "PARENT/AMI"
  'X       ' "AUTRE"
  '?       ' "NON REPONSE"
 /PN23A   
  'A' "MEDECIN"
  '?' "NON REPONSE"
 /PN23C   
  'C' "INFIRMIERE/INFIRMIER"
  '?' "NON REPONSE"
 /PN23D   
  'D' "ACOUCHEUSE /  SAGE FEMME"
  '?' "NON REPONSE"
 /PN23F   
  'F' "ACCOUCHEUSE TRADITIONNELLE"
  '?' "NON REPONSE"
 /PN23G   
  'G' "AGENT DE SANTE COMMUNAUTAIRE"
  '?' "NON REPONSE"
 /PN23H   
  'H' "PARENT/AMI"
  '?' "NON REPONSE"
 /PN23X   
  'X' "AUTRE"
  '?' "NON REPONSE"
 /PN23NR  
  '?' "NON REPONSE"
 /PN24    
    11 "DOMICILE DE L’ENQUETEE"
    12 "AUTRE DOMICILE"
    21 "HOPITAL GOUVERNEMENTAL"
    22 "CLINIQUE / CENTRE DE SANTE GOUV"
    23 "POSTE DE SANTE GOUVERNEMENTAL"
    26 "AUTRE PUBLIC"
    31 "HOPITAL PRIVE"
    32 "CLINIQUE PRIVEE"
    33 "MATERNITE PRIVEE"
    36 "AUTRE PRIVATE MEDICAL"
    96 "AUTRE"
    99 "NON REPONSE"
 /PN25A   
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /PN25B   
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /PN25C   
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /PN27    
     1 "OUI"
     2 "NON"
     8 "NSP"
     9 "NON REPONSE"
 /PN29    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /PN30    
     1 "OUI"
     2 "NON"
     9 "NON REPONSE"
 /MA1     
     1 "OUI, MARIEE ACTUELLEMENT"
     2 "OUI, VIT ACTUELLEMENT AVEC UN PARTENAIRE"
     3 "NON, PAS EN UNION"
     9 "NON REPONSE"
 /MA5     
     1 "OUI, FORMELLEMENT MARIEE"
     2 "OUI, A VECU EN UNION"
     3 "NON"
     9 "NON REPONSE"
 /MA6     
     1 "VEUVE"
     2 "DIVORCEE"
     3 "SEPAREE"
 /MA7     
     1 "SEULEMENT UNE FOIS"
     2 "PLUS D’UNE FOIS"
     9 "NON REPONSE"
 /MA8M    
     1 "JANVIER"
     2 "FÉVRIER"
     3 "MARS"
     4 "AVRIL"
     5 "MAI"
     6 "JUIN"
     7 "JUILLET"
     8 "AOUT"
     9 "SEPTEMBRE"
    10 "OCTOBRE"
    11 "NOVEMBRE"
    12 "DECEMBRE"
    98 "NSP"
    99 "NON REPONSE"
 /MA8Y    
  9998 "NSP"
  9999 "NON REPONSE"
 /TEF5    
     1 "OUI"
     2 "NON"
 /CAS1    
     1 "DIFFICILE"
     2 "PAS DIFFICILE"
     8 "NSP"
 /CAS2    
  'A          ' "FRAIS DE TRANSPORT ELEVES POUR MOI"
  'B          ' "ETABLISSEMENT EST LOIN / DIFFICILE D’ACCES"
  'C          ' "FRAIS DES SERVICES  DE SOINS ELEVES POUR MOI"
  'D          ' "CHARGE DE LA GARDE D'ENFANTS"
  'E          ' "CHARGE DU TRAVAIL (INTERIEUR / EXTERIEUR  MAISON)"
  'F          ' "MARI / PARTENAIRE N’AUTORISE PAS"
  'G          ' "PERSONNEL DE L'ETABLISSEMENT INSOLENT....."
  'H          ' "PAS DE PERSONNEL FEMININ  DANS L’ETABLISSMENT"
  'I          ' "LONGUE ATTENTE DANS LES LOCAUX"
  'X          ' "AUTRE (préciser)"
  'Z          ' "NSP/PAS SUR"
 /CAS2A   
  'A' "FRAIS DE TRANSPORT ELEVES POUR MOI"
 /CAS2B   
  'B' "ETABLISSEMENT EST LOIN / DIFFICILE D’ACCES"
 /CAS2C   
  'C' "FRAIS DES SERVICES  DE SOINS ELEVES POUR MOI"
 /CAS2D   
  'A' "CHARGE DE LA GARDE D'ENFANTS"
 /CAS2E   
  'E' "CHARGE DU TRAVAIL (INTERIEUR / EXTERIEUR MAISON)"
 /CAS2F   
  'F' "MARI / PARTENAIRE N’AUTORISE PAS"
 /CAS2G   
  'G' "PERSONNEL DE L'ETABLISSEMENT INSOLENT"
 /CAS2H   
  'H' "PAS DE PERSONNEL FEMININ  DANS L’ETABLISSMENT"
 /CAS2I   
  'I' "LONGUE ATTENTE DANS LES LOCAUX"
 /CAS2X   
  'X' "AUTRE (préciser"
 /CAS2Z   
  'Z' "NSP/PAS SUR"
 /CAS3    
     1 "OUI"
     2 "NON"
     8 "NSP"
 /CAS4    
     1 "PLUS D'UNE FOIS PAR MOIS"
     2 "UNE FOIS PAR MOIS"
     3 "TOUS LES 2-3 MOIS"
     4 "TOUS LES 6 MOIS OU PLUS"
     5 "JAMAIS"
    96 "AUTRE"
    98 "NSP/PAS SUR"
 /AC1     
     1 "OUI"
     2 "NON"
     8 "NSP"
 /AC2     
     1 "IMPORTANT"
     2 "PAS IMPORTANT"
     8 "NSP"
 /AC3     
  'A     ' "AVOIR UNE GROSSESSE SAINE"
  'B     ' "APPRENDRE A PREVENIR LES RISQUES POUR LA  MAMAN ET LE BEBE"
  'C     ' "OBTENIR DES MOUSTIQUAIRES ET DES VITAMINES COMPRENDRE COMMENT / OU DONNER"
  'D     ' " NAISSANCE"
  'X     ' "AUTRE (préciser"
  'Z     ' "NSP/PAS SURE"
 /AC3A    
  'A' "AVOIR UNE GROSSESSE SAINE"
 /AC3B    
  'B' "APPRENDRE A PREVENIR LES RISQUES POUR LA  MAMAN ET LE BEBE"
 /AC3C    
  'C' "OBTENIR DES MOUSTIQUAIRES ET DES VITAMINES."
 /AC3D    
  'D' "COMPRENDRE COMMENT / OU DONNER NAISSANCE"
 /AC3X    
  'X' "AUTRE (préciser"
 /AC3Z    
  'Z' "NSP/PAS SURE"
 /AC4     
    10 "PREMIER TRIMESTRE"
    11 "DES QU'ELLE SAIT QU'ELLE EST ENCEINTE"
    12 "QUAND LE BEBE COMMENCE A BOUGER"
    13 "QUAND ELLE SAIGNE"
    14 "QUAND ELLE SENT QUE QUELQUE CHOSE NE VA PAS BIEN AVEC ELLE OU AVEC SON BEBE"
    15 "JUSTE AVANT L’ACOUCHEMENT"
    96 "AUTRE (préciser"
    98 "NSP/PAS SURE"
 /AC5     
    10 "UNE VISITE"
    11 "DEUX VISITES"
    12 "TROIS VISITES"
    13 "QUATRE VISITES ET PLUS"
    14 "HUIT VISITES ET PLUS"
    15 "UNE VISITE CHAQUE MOIS DE GROSSESSE"
    96 "AUTRE (préciser"
    98 "NSP/PAS SURE"
 /AC6     
  'A      ' "MERE SAIT QUOI FAIRE"
  'B      ' "PARENT PEUT FOURNIR DES CONSEILS"
  'C      ' "PAS DE BESOIN SI LA FEMME A DEJA MIS AU MONDE"
  'D      ' "AUCUN RISQUE"
  'E      ' "CROYANCES RELIGIEUSES ET CULTURELLES"
  'X      ' "AUTRE (préciser)"
  'Z      ' "NSP/PAS SURE"
 /AC6A    
  'A' "MERE SAIT QUOI FAIRE"
 /AC6B    
  'B' "PARENT PEUT FOURNIR DES CONSEILS"
 /AC6C    
  'C' "PAS DE BESOIN SI LA FEMME A DEJA MIS AU MONDE"
 /AC6D    
  'D' "AUCUN RISQUE"
 /AC6E    
  'E' "CROYANCES RELIGIEUSES ET CULTURELLES"
 /AC6X    
  'X' "AUTRE (préciser"
 /AC6Z    
  'Z' "NSP/PAS SURE"
 /DC1     
  'A    ' "PERSONNEL DE SANTE (MEDECIN, INFIRMIERE SAGE-FEMME)"
  'B    ' "ACCOUCHEUSE TRADITIONNELLE / ACCOUCHEUSE COMMUNAUTAIRE"
  'C    ' "PARENTE / AMIE"
  'X    ' "AUTRE (préciser"
  'Z    ' "NSP/PAS SURE"
 /DC1A    
  'A' "PERSONNEL DE SANTE (MEDECIN, INFIRMIERE, SAGE-FEMME)"
 /DC1B    
  'B' "ACCOUCHEUSE TRADITIONNELLE / ACCOUCHEUSE COMMUNAUTAIRE"
 /DC1C    
  'C' "PARENTE / AMIE"
 /DC1X    
  'X' "AUTRE (préciser)"
 /DC1Z    
  'Z' "NSP/PAS SURE"
 /DC2     
     1 "CENTRE DE SANTE (HOPITAL, CENTRE DE SANTE, CLINIQUE, ETC.)"
     2 "A DOMICILE"
     3 "AU DOMICILE D'UN PARENT / AMI"
     6 "AUTRE (préciser)"
     8 "NSP/PAS SURE"
 /BR1     
     1 "OUI"
     2 "NON"
     8 "NSP"
 /BR2     
     1 "OUI"
     2 "NON"
     8 "NSP"
 /BR3     
     1 "IMPORTANT"
     2 "PAS IMPORTANT"
     8 "NSP"
 /BR4     
  'A        ' "ACCÈS AUX SERVICES DE SANTÉ"
  'B        ' "ACCÈS À L’ÉDUCATION"
  'C        ' "AVOIR UNE IDENTITÉ JURIDIQUE"
  'D        ' "AVOIR UN DOCUMENT"
  'E        ' "DONNER UN NOM OFFICIEL"
  'F        ' "DONNEZ-LA CITOYENNETÉ/ NATIONALITÉ"
  'G        ' "POUR POUVOIR VOYAGER"
  'X        ' "AUTRE (préciser)"
  'Z        ' "NSP /PAS SÛRE"
 /BR4A    
  'A' "ACCÈS AUX SERVICES DE SANTÉ"
 /BR4B    
  'B' "ACCÈS À L’ÉDUCATION"
 /BR4C    
  'C' "AVOIR UNE IDENTITÉ JURIDIQUE"
 /BR4D    
  'D' "AVOIR UN DOCUMENT"
 /BR4E    
  'E' "DONNER UN NOM OFFICIEL"
 /BR4F    
  'F' "DONNEZ-LA CITOYENNETÉ  / NATIONALITÉ"
 /BR4G    
  'G' "POUR POUVOIR VOYAGER"
 /BR4X    
  'X' "AUTRE (préciser"
 /BR4Z    
  'Z' "NSP /PAS SÛRE"
 /BR5     
  'A   ' "NE FAIT AUCUNE DIFFERENCE"
  'B   ' "A DEJA UN NOM"
  'X   ' "AUTRE (préciser"
  'Z   ' " NSP / PAS SURE"
 /BR5A    
  'A' "NE FAIT AUCUNE DIFFERENCE"
 /BR5B    
  'B' "A DEJA UN NOM"
 /BR5X    
  'X' "AUTRE (préciser"
 /BR5Z    
  'Z' "NSP / PAS SURE"
 /BR6     
     1 "DIFFICILE"
     2 "PAS DIFFICILE"
     8 "NSP"
 /BR7     
  'A           ' "NE SAIT PAS QUE C’EST UN REQUIS LÉGAL"
  'B           ' "PAS ASSEZ D'ARGENT"
  'C           ' "DISTANCE"
  'D           ' "PROCESSUS TROP LONG / COMPLEXE"
  'E           ' "DOCUMENTS INCOMPLETS"
  'F           ' "PÈRE ABSENT"
  'G           ' "L'ENFANT N'A PAS ENCORE UN NOM"
  'H           ' "PARLER DIFFÉRENTES LANGUES"
  'I           ' "MANQUE D'ALPHABETISATION"
  'J           ' "JE NE SAIS PAS COMMENT  INSCRIRE"
  'X           ' "AUTRE (préciser)"
  'Z           ' "NE SAIT PAS / PAS SURE"
 /BR7A    
  'A' "NE SAIT PAS QUE C’EST UN REQUIS LÉGAL"
 /BR7B    
  'B' "PAS ASSEZ D'ARGENT"
 /BR7C    
  'C' "DISTANCE"
 /BR7D    
  'D' "PROCESSUS TROP LONG / COMPLEXE"
 /BR7E    
  'E' "DOCUMENTS INCOMPLETS"
 /BR7F    
  'F' "PÈRE ABSENT"
 /BR7G    
  'G' "L'ENFANT N'A PAS ENCORE UN NOM"
 /BR7H    
  'H' "PARLER DIFFÉRENTES LANGUE"
 /BR7I    
  'I' "MANQUE D'ALPHABETISATION"
 /BR7J    
  'J' "JE NE SAIS PAS COMMENT  INSCRIRE"
 /BR7X    
  'X' "AUTRE (préciser)"
 /BR7Z    
  'Z' "NE SAIT PAS / PAS SURE"
 /IM1     
     1 "OUI"
     2 "NON"
     8 "NSP"
 /IM2     
     1 "IMPORTANT"
     2 "PAS IMPORTANT"
     8 "NSP"
 /IM3     
  'A      ' "PREVENIR UNE MALADIE"
  'B      ' "PRÉVENIR LA MORT"
  'C      ' "RESTER SAIN"
  'D      ' "BIEN SE DEVELOPPER"
  'E      ' "POUR CONSTRUIRE SYSTEME IMMUNITAIRE"
  'X      ' "AUTRE (PRECISER"
  'Z      ' "NSP/PAS SURE"
 /IM3A    
  'A' "PREVENIR UNE MALADIE"
 /IM3B    
  'B' "PRÉVENIR LA MORT"
 /IM3C    
  'C' "RESTER SAIN"
 /IM3D    
  'D' "BIEN SE DEVELOPPER"
 /IM3E    
  'E' "POUR CONSTRUIRE SYSTEME IMMUNITAIRE"
 /IM3X    
  'X' "AUTRE (PRECISER)"
 /IM3Z    
  'Z' "NSP/PAS SURE"
 /IM4     
  'A                ' "POLIOMYELITE"
  'B                ' "ROUGEOLE"
  'C                ' "DIPHTERIE"
  'D                ' "PERTUSSIS (COQUELUCHE)"
  'E                ' "RUBEOLE (ROUGEOLE ALLEMANDE)"
  'F                ' "OREILLONS"
  'G                ' "TETANOS"
  'H                ' "ROTAVIRUS / DIARRHEE"
  'I                ' "HAEMOPHILUS INFLUENZAE DE TYPE B"
  'J                ' "TUBERCULOSE"
  'K                ' "TYPHOÏDE"
  'L                ' "HEPATITE"
  'M                ' "FIEVRE JAUNE"
  'N                ' "VIH / SIDA"
  'O                ' "PALUDISME"
 /IM4A    
  'A' "POLIOMYELITE"
 /IM4B    
  'B' "ROUGEOLE"
 /IM4C    
  'C' "DIPHTERIE"
 /IM4D    
  'D' "PERTUSSIS (COQUELUCHE)"
 /IM4E    
  'E' "RUBEOLE (ROUGEOLE ALLEMANDE"
 /IM4F    
  'F' "OREILLONS"
 /IM4G    
  'G' "TETANOS"
 /IM4H    
  'H' "ROTAVIRUS / DIARRHEE"
 /IM4I    
  'I' "HAEMOPHILUS INFLUENZAE DE TYPE B"
 /IM4J    
  'J' "TUBERCULOSE"
 /IM4K    
  'K' "TYPHOÏDE"
 /IM4L    
  'L' "HEPATITE"
 /IM4M    
  'M' "FIEVRE JAUNE"
 /IM4N    
  'N' "VIH / SIDA"
 /IM4O    
  'O' "PALUDISME"
 /IM4X    
  'X' "AUTRE (préciser)"
 /IM4Z    
  'Z' "NE SAIT PAS / PAS SURE"
 /IM5     
     1 "1 CONTACT"
     2 "2 CONTACTS"
     3 "3 CONTACTS"
     4 "4 CONTACTS"
     5 "5 CONTACTS"
     6 "6 CONTACTS"
     8 "NSP/PAS SUR"
 /IM6     
  'A         ' "A LA NAISSANCE"
  'B         ' "6 SEMAINES"
  'C         ' "10 SEMAINES"
  'D         ' "14 SEMAINES"
  'E         ' "9 MOIS"
  'F         ' "15-18 MOIS"
  'G         ' "CAMPAGNES"
  'H         ' "TOUS LES MOIS AU COURS DE LA PREMIÈRE ANNÉE"
  'X         ' "AUTRE (préciser"
  'Z         ' "NSP/PAS SURE"
 /IM6A    
  'A' "A LA NAISSANCE"
 /IM6B    
  'B' "6 SEMAINES"
 /IM6C    
  'C' "10 SEMAINES"
 /IM6D    
  'D' "14 SEMAINES"
 /IM6E    
  'E' "9 MOIS"
 /IM6F    
  'F' "15-18 MOIS"
 /IM6G    
  'G' "CAMPAGNES"
 /IM6H    
  'H' "TOUS LES MOIS AU COURS DE LA PREMIÈRE ANNÉE"
 /IM6X    
  'X' "AUTRE (préciser)"
 /IM6Z    
  'Z' "NSP/PAS SURE"
 /IM7     
  'A              ' "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE LE VACCIN"
  'B              ' "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE 2E OU 3E DOSE"
  'C              ' "ENFANT N’EST PAS A L’AISE"
  'D              ' "PEUR DES EFFETS SECONDAIRES"
  'E              ' "MERE TROP OCCUPEE"
  'F              ' "LE MOMENT POUR LE VACCIN N’EST PAS CONVENABLE"
  'G              ' "MERE N’EST PAS A L’AISE"
  'H              ' "PAS D'ARGENT POUR PAYER  LES CHARGES"
  'I              ' "LIEU DE VACCINATION TROP LOIN ET PAS D’ARGENT SUFFISANT POUR PAYER LE TRANSPORT"
  'J              ' "AUCUN VACCIN DISPONIBLE"
  'K              ' "AUCUN PERSONNEL DE LA SANTE DISPONIBLE"
  'M              ' "PARENTS PEUVENT OUBLIER"
  'N              ' "CENTRE DEBORDE DE PATIENTS/LONGUE ATTENTE"
  'X              ' "AUTRE(préciser)"
  'Z              ' "NSP/PAS SURE"
 /IM7A    
  'A' "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE LE VACCIN"
 /IM7B    
  'B' "NE SAIT PAS QUE L'ENFANT DEVRAIT PRENDRE 2E OU 3E DOSE"
 /IM7C    
  'C' "ENFANT N’EST PAS A L’AISE"
 /IM7D    
  'D' "PEUR DES EFFETS SECONDAIRES"
 /IM7E    
  'E' "MERE TROP OCCUPEE"
 /IM7F    
  'F' "LE MOMENT POUR LE VACCIN N’EST PAS CONVENABLE"
 /IM7G    
  'G' "MERE N’EST PAS A L’AISE"
 /IM7H    
  'H' "PAS D'ARGENT POUR PAYER LES CHARGES"
 /IM7I    
  'I' "LIEU DE VACCINATION TROP LOIN ET PAS D’ARGENT SUFFISANT POUR PAYER LE TRANSPORT"
 /IM7J    
  'J' "AUCUN VACCIN DISPONIBLE"
 /IM7K    
  'K' "AUCUN PERSONNEL DE LA SANTE DISPONIBLE"
 /IM7M    
  'M' "PARENTS PEUVENT OUBLIER"
 /IM7N    
  'N' "CENTRE DEBORDE DE PATIENTS/LONGUE ATTENTE"
 /IM7X    
  'X' "AUTRE(préciser"
 /IM7Z    
  'Z' "NSP/PAS SURE"
 /IM8     
  'A    ' "EFFETS SECONDAIRES"
  'B    ' "ENFANTS PEUVENT TOMBER MALADES"
  'C    ' "RAISONS RELIGIEUSES"
  'X    ' "AUTRE (préciser"
  'Z    ' "NSP/PAS SURE"
 /IM8A    
  'A' "EFFETS SECONDAIRES"
 /IM8B    
  'B' "ENFANTS PEUVENT TOMBER MALADES"
 /IM8C    
  'C' "RAISONS RELIGIEUSES"
 /IM8X    
  'X' "AUTRE (préciser"
 /IM8Z    
  'Z' "NSP/PAS SURE"
 /IM9     
  'A     ' "ETABLISSEMENT DE SANTE / CLINIQUE"
  'B     ' "CENTRES DE VACCINATION DE PROXIMITE"
  'C     ' "CLINIQUE MOBILE"
  'D     ' "PENDANT LES CAMPAGNES DE VACCINATION"
  'X     ' "AUTRE (préciser)"
  'Z     ' "NSP/PAS SURE"
 /IM9A    
  'A' "ETABLISSEMENT DE SANTE / CLINIQUE"
 /IM9B    
  'B' "CENTRES DE VACCINATION DE PROXIMITE"
 /IM9C    
  'C' "CLINIQUE MOBILE"
 /IM9D    
  'D' "PENDANT LES CAMPAGNES DE VACCINATION"
 /IM9X    
  'X' "AUTRE (préciser)"
 /IM9Z    
  'Z' "NSP/PAS SURE"
 /IM10    
   998 "NSP"
 /IM10U   
     1 "MINUTES"
     2 "HEURES"
     9 "NSP"
 /IM10N   
    98 "NSP"
 /VIT1    
     1 "OUI"
     2 "NON"
     8 "NSP"
 /VIT2    
     1 "IMPORTANT"
     2 "PAS IMPORTANTS"
     8 "NSP"
 /VIT3    
  'A      ' "ÉVITER LES MALADIES"
  'B      ' "ÉVITER LA MORT"
  'C      ' "RESTER EN BONNE SANTE"
  'D      ' "TRAITEMENT D’UNE MALADIE"
  'E      ' "DEVELOPPER L’IMMUNITÉ"
  'X      ' "AUTRE (Préciser)"
  'Z      ' "NSP/PAS SURE"
 /VIT3A   
  'A' "ÉVITER LES MALADIES"
 /VIT3B   
  'B' "ÉVITER LA MORT"
 /VIT3C   
  'C' "RESTER EN BONNE SANTE"
 /VIT3D   
  'D' "TRAITEMENT D’UNE MALADIE"
 /VIT3E   
  'E' "DEVELOPPER L’IMMUNITÉ"
 /VIT3X   
  'X' "AUTRE (Préciser"
 /VIT3Z   
  'Z' "NSP/PAS SURE"
 /VIT4    
     1 "À LA NAISSANCE"
     2 "AU PREMIER MOIS"
     3 "À 6 MOIS"
     4 "A 1 AN"
     5 "SUR CONSEILS D’UN AGENT DE SANTE"
     6 "A N’IMPORTE QUEL MOMENT"
    96 "AUTRE (préciser)"
    98 "NSP/PAS SURE"
 /VIT5    
     1 "JUSQU'A 1 an"
     2 "JUSQU'À 2 ANS"
     3 "JUSQU'A 5 ANS"
     4 "JUSQU'À 10 ANS"
     5 "JUSQU'A 15 ANS OU PLUS"
    96 "AUTRE (préciser"
    98 "NSP/PAS SURE"
 /VIT6    
  'A    ' "CE N’EST PAS NÉCESSAIRE"
  'B    ' "ENFANT MANGE BIEN"
  'C    ' "CROYANCE RELIGIEUSE"
  'X    ' "AUTRE (préciser)"
  'Z    ' "NSP/PAS SURE"
 /VIT6A   
  'A' "CE N’EST PAS NÉCESSAIRE"
 /VIT6B   
  'B' "ENFANT MANGE BIEN"
 /VIT6C   
  'C' "CROYANCE RELIGIEUSE"
 /VIT6X   
  'X' "AUTRE (préciser)"
 /VIT6Z   
  'Z' "NSP/PAS SURE"
 /DEW1    
     1 "OUI"
     2 "NON"
     8 "NSP"
 /DEW2    
     1 "OUI, IMPORTANT"
     2 "PAS IMPORTANT"
     8 "NSP"
 /DEW3    
  'A     ' "TUER LES PARASITES /ELIMINER LES VERS"
  'B     ' "PRÉVENIR LES MALADIES"
  'C     ' "LES AIDER À RESTER EN SANTÉ"
  'D     ' "REMEDE DE LA MALADIE"
  'X     ' "AUTRE (préciser"
  'Z     ' "NSP/PAS SURE"
 /DEW3A   
  'A' "TUER LES PARASITES /ELIMINER LES VERS"
 /DEW3B   
  'B' "PRÉVENIR LES MALADIES"
 /DEW3C   
  'C' "LES AIDER À RESTER EN SANTÉ"
 /DEW3D   
  'D' "REMEDE DE LA MALADIE"
 /DEW3X   
  'X' "AUTRE (préciser)"
 /DEW3Z   
  'Z' "NSP/PAS SURE"
 /DEW4    
    10 "A LA NAISSANCE"
    11 "À 6 MOIS"
    12 "À 12 MOIS"
    13 "À 2 ANS"
    14 "À 5 ANS"
    15 "SUR CONSEILS D’UN AGENT DE SANTE"
    16 "À N’IMPORTE QUEL MOMENT"
    96 "AUTRE (préciser)"
    98 "NSP/PAS SURE"
 /DEW5    
     1 "UNE FOIS PAR MOIS"
     2 "TOUS LES 6 MOIS"
     3 "UNE FOIS PAR AN"
     4 "SUR CONSEILS DE L’AGENT DE SANTE"
     5 "À TOUT MOMENT"
     6 "AUTRE (préciser)"
     8 "NSP/PAS SURE"
 /DEW6    
     1 "JUSQU'A 1 AN"
     2 "JUSQU'À 2 ANS"
     3 "JUSQU'A 5 ANS"
     4 "JUSQU'À 10 ANS"
     5 "DE 10 À 15 ANS OU PLUS"
     6 "AUTRE (préciser"
     8 "NSP/PAS SURE"
 /DEW7    
  'A     ' "NÉCESSAIRE"
  'B     ' "IL N’Y A PAS DE VERS AUTOUR"
  'C     ' "ENFANT N’EST PAS EXPOSE / PAS DE CONTACT AVEC LE TERRAIN"
  'D     ' "CROYANCE RELIGIEUSE"
  'X     ' "AUTRE (préciser"
  'Z     ' "NSP/PAS SURE"
 /DEW7A   
  'A' "NÉCESSAIRE"
 /DEW7B   
  'B' "IL N’Y A PAS DE VERS AUTOUR"
 /DEW7C   
  'C' "ENFANT N’EST PAS EXPOSE / PAS DE CONTACT AVEC LE TERRAIN"
 /DEW7D   
  'D' "CROYANCE RELIGIEUSE"
 /DEW7X   
  'X' "AUTRE (préciser"
 /DEW7Z   
  'Z' "NSP/PAS SURE"
 /SAN1    
    11 "CHASSE, CHASSE D’EAU"
    12 "LATRINE A FOSSE"
    13 "L’AIR LIBRE"
    14 "DECHETS DOMESTIQUES"
    96 "AUTRE (préciser)"
    98 "NSP/PAS SURE"
 /SAN2    
     1 "OUI, IL Y A UN RISQUE"
     2 "NON, AUCUN RISQUE"
     8 "NSP"
 /SAN3    
     1 "IMPREGNATION / LAIDEUR / GROSSIERETE"
     2 "MAUVAISE ODEUR /DEGOUT"
     3 "RISQUE POUR LA SANTÉ / PROPAGATION DE MALADIES (CHOLÉRA, DIARRHÉE, ETC)"
     4 "CONTAMINATION DES SOURCES D'EAU"
     6 "AUTRE (préciser"
     8 "NSP/PAS SURE"
 /SAN4    
  'A        ' "PALUDISME"
  'B        ' "TUBERCULOSE"
  'C        ' "FIEVRE TYPHOÏDE"
  'D        ' "FIEVRE JAUNE"
  'E        ' "CHOLERA"
  'F        ' "DIARRHÉE"
  'G        ' "DYSENTERIE"
  'X        ' "AUTRE (Préciser)"
  'Z        ' "NSP/PAS SURE"
 /SAN4A   
  'A' "PALUDISME"
 /SAN4B   
  'B' "TUBERCULOSE"
 /SAN4C   
  'C' "FIEVRE TYPHOÏDE"
 /SAN4D   
  'D' "FIEVRE JAUNE"
 /SAN4E   
  'E' "CHOLERA"
 /SAN4F   
  'F' "DIARRHÉE"
 /SAN4G   
  'G' "DYSENTERIE"
 /SAN4X   
  'X' "AUTRE (Préciser)"
 /SAN4Z   
  'Z' "NSP/PAS SURE"
 /SAN5    
     1 "OUI, IMPORTANT"
     2 "PAS IMPORTANT"
     8 "NSP"
 /HD1     
     1 "OUI, UN AVANTAGE"
     2 "AUCUN AVANTAGE"
     8 "NSP"
 /HD2     
  'A     ' "NETTOYER LA SALETE"
  'B     ' "PRÉVENIR LES MALADIES OU LES INFECTIONS GERMINALES"
  'C     ' "MAINS PROPRES / ELEGANCE"
  'D     ' "PAIX DE L’ESPRIT"
  'X     ' "AUTRE (préciser"
  'Z     ' "NSP/PAS SURE"
 /HD2A    
  'A' "NETTOYER LA SALETE"
 /HD2B    
  'B' "PRÉVENIR LES MALADIES OU LES INFECTIONS GERMINALES"
 /HD2C    
  'C' "MAINS PROPRES / ELEGANCE"
 /HD2D    
  'D' "PAIX DE L’ESPRIT"
 /HD2X    
  'X' "AUTRE (préciser)"
 /HD2Z    
  'Z' "NSP/PAS SURE"
 /HD3     
  'A       ' "AVANT REPAS"
  'B       ' "AVANT DE NOURRIR UN ENFANT"
  'C       ' "PRÉPARER / SERVIR UN REPAS"
  'D       ' "APRÈS TOILETTES / LATRINES"
  'E       ' "APRÈS LE NETTOYAGE DES FESSES D’UN ENFANT OU LE CHANGEMENT DE COUCHE"
  'F       ' "APRÈS LES REPAS"
  'X       ' "AUTRE (préciser"
  'Z       ' "NSP/PAS SURE"
 /HD3A    
  'A' "AVANT REPAS"
 /HD3B    
  'B' "AVANT DE NOURRIR UN ENFANT"
 /HD3C    
  'C' "PRÉPARER / SERVIR UN REPAS"
 /HD3D    
  'D' "APRÈS TOILETTES / LATRINES"
 /HD3E    
  'E' "APRÈS LE NETTOYAGE DES FESSES D’UN ENFANT OU LE CHANGEMENT DE COUCHE"
 /HD3F    
  'F' "APRÈS LES REPAS"
 /HD3X    
  'X' "AUTRE (préciser"
 /HD3Z    
  'Z' "NSP/PAS SURE"
 /HD4     
     1 "OUI, C’EST PRATIQUE"
     2 "NON, CE N’EST PAS PRATIQUE"
     3 "PARFOIS PRATIQUE, PARFOIS PAS"
     8 "NSP"
.
EXECUTE.
